### ISSUE TITLE
Customer credits allow for setting negative quantities

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#2756] opened 2020-04-23 00:44 UTC
## Describe the bug

This is a big oversight on my side! Customer credits are automatically confirmed, and therefore will automatically adjust real stock values instantly. This means you're able to reduce the amount of stock coming in, which may have been used elsewhere.

### To reproduce

*Create a supplier credit to your mobile store, which will create a customer credit on the mobile side*
1. Go to the customer credit and adjust the values so that you have 100 total stock for that item (or 1000 if you have more than 100 etc..)
2. Click on back, and navigate to a customer invoice (unfinalized).
3. Add the same item that you edited in the customer credit, editing the quantity to be the maximum allowed (i.e. 100 or 1000).
4. Now, go back to the customer credit and reduce the amount to 10.
5. See error

### Expected behaviour

The app shouldn't crash and you shouldn't be able to set negative values.

### Proposed Solution

This was unexpected as I didn't know that customer credits were automatically confirmed! A bit annoying - similar problem as we have with stocktakes and customer invoices. Example: Snapshot is the quantity at the time of finalizing, not from the time of creation. So, when you make a stocktake, then go edit quantities and go back to the stocktake, the snapshot might be wrong - so we auto adjust on navigating. That's less ideal to do for a CI, I think. But possible.

Desktop solution is to:

<img width="627" alt="image" src="https://user-images.githubusercontent.com/35858975/80040472-459bc080-854e-11ea-850c-cf90ae35421c.png">
When trying to edit the customer credit line

Then shows this:
<img width="497" alt="image" src="https://user-images.githubusercontent.com/35858975/80040516-5cdaae00-854e-11ea-89f3-7679d3304fab.png">

I am thinking for the easiest solution, some method of restricting the editable quantity of the customer credit so you can't reduce it low enough, and it just adjusts to the lowest amount when editing - similar to how a CI editing works - if you only have 100, and you try issue 101, it goes to 0 (not the greatest UX, but easy solution for now?). Something along the lines of having the line be disabled when there is an unfinalized CI line with that particular item. It's not great because it offers 0 feedback for the user,  but it's a start of a solution, at least 🤣 Possibly allow for editing but default back if `hasStockIssued` is true, or something, and use a toast to explain why..?

### Version and device info

- App version: 5.0.0-RC2
- Tablet model: N/A
- OS version: N/A

### Additional context

@wlthomson thoughts?

**Comment by wlthomson** [comment] 2020-04-23 01:03
@joshxg Good thing you spotted this!

I think a good solution is to make customer credits basically "read-only". As the stock is updated on confirmation, AFAIK finalisation doesn't really do much except for "lock" the transaction. 

One option would be to lock credit transactions (still allow finalising, but I think would be somewhat redundant?)

Other option would just be to finalise the customer credits on incoming sync?

Can always iterate on this, and we're still adding functionality in that the user can see where the stock changes came from (which they previously couldn't).

Does that make sense? Could be missing something here!

**Comment by joshxg** [comment] 2020-04-23 01:13
yup all right.

the idea around finalising automatically does seem nice actually - since making it disabled means it's really just extra things a user has to do for nothing. I like that solution. Maybe we try get someone else to weigh in 🤣 

@mark-prins 

To summarize:

*Problem*
- We're showing customer credits now. These are auto-confirmed, which cause issues when editing (i.e. make CC line quantity of 10, make a CI with quantity 10, go back and edit CC with quantity 1 - now you have negative -9 quantity of the item)
- Desktop solution: Don't allow editing inline, have to double click to open a popup to edit. If it has a CI line for that item, don't allow editing

*Our possible solutions*
- Just auto finalise on sync and don't allow editing (You cant make them, only get them through sync)
- Always disabled, except for finalising
- Don't allow editing if there is a CI line for that item (Harder to give feedback on a tablet for this, not great UX)

**Comment by mark-prins** [comment] 2020-04-24 02:55
I'd prefer (3) but that is too hard in mobile due to UI constraints as you say.

So I'd go with (1) and auto finalise on sync. That fits in with the standard model of not editing finalised items. We'd have to document this, so that our future selves can remember why editing of confirmed `cc`s is a bad idea.

Option (1) is similar to option (4) which is don't allow editing of confirmed *or* finalised customer credits, but better, I think.

**Comment by wlthomson** [comment] 2020-04-27 03:17
Fixed by #2772.

**Closed by wlthomson** 2020-04-27 03:17 UTC
Labels: Bug: development, Docs: not needed, Effort: small, Priority: release blocker

**Comment by nishaSussol** [comment] 2020-04-29 11:55
## TESTING
Tested in mobile v5.0.0RC2

## Setup 
- [x] Create a supplier credit for mobile store.
- [x] Manually sync mobile.
- [x] Navigate to customer invoices and toggle to `"Past"`.

## Test cases
- [x] The customer credit which corresponds to the supplier credit is displayed
- [x] The customer credit is finalised and cannot be edited **-FAIL-**
Its NOT finalised, and can be edited.
Plus,
@wlthomson, after manually syncing, there is a sync error:
![Screenshot_2020-04-29-16-39-32](https://user-images.githubusercontent.com/59193490/80592777-b3108b00-8a3f-11ea-8681-a81930778994.png)

**Comment by wlthomson** [comment] 2020-04-30 04:14
@nishaSussol Thanks for testing and making the issue! Have labelled the new issue as a release blocker and made a fix (#2803). Moving this to done :+1:.
