### ISSUE TITLE
Lines added to prescription being entered shouldn't show in patient history

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#3326] opened 2021-01-11 20:37 UTC
## Describe the bug

Currently if you make a prescription and add items to it, when you click patient history in the same window, the lines you've just added show as history. But they are the present, not the past!

### To reproduce

1. Dispense to patient, select prescriber, be on the screen to add items
2. Click on the patient history button. If no history observe no lines: ![Screen Shot 2021-01-12 at 9 27 39 AM](https://user-images.githubusercontent.com/7684221/104234664-a1312400-54b8-11eb-8cae-580aafdd390d.png)
3. Exit history, add a line: 
![Screen Shot 2021-01-12 at 9 27 52 AM](https://user-images.githubusercontent.com/7684221/104234667-a1c9ba80-54b8-11eb-8fef-8b10e4c35a5b.png)
4. View history again and see the lines you just added. They probably shouldn't be there: ![Screen Shot 2021-01-12 at 9 28 02 AM](https://user-images.githubusercontent.com/7684221/104234659-9ececa00-54b8-11eb-823c-3a6692c2981b.png)

### Expected behaviour

Don't see lines of prescription being created.

### Proposed Solution

**TBD** but I assume the history list should probably just filter by finalised prescriptions when querying for the transaction items.

### Version and device info

- App version: 6.0.0
- Tablet model: emulator
- OS version: Android 11

**Comment by katherine-sussol** [comment] 2021-06-17 22:56
Duplicate of https://github.com/openmsupply/mobile/issues/2746 (and done 🥳 )

**Closed by katherine-sussol** 2021-06-17 22:56 UTC
Labels: Bug: production, Closed: duplicate, Docs: not needed, Effort: small, Priority: normal
