### ISSUE TITLE
Removing stock take > App crashed

### ISSUE THREAD

**Issue by bijaySussol** [openmsupply/mobile#3099] opened 2020-08-14 12:35 UTC
## Describe the bug

Removing the stock take app crashed

### To reproduce

1. Create new stock take
2. Choose any 3 lines
3. Hit **Create**
4. Put the **Actual Quantity**
5. Tap on **Manage stocktake**
6. Sync it
7. Go back to stock take list
8. from the stock take check **Remove** against that stock take
9. Select that row take you to stock take input window
10. Tap on **Manage stocktake**
11. Unselect one line against from the existing stock take
12. Sync it
13. Go back
14. Click on **Remove** from the alert box which says: **Are you sure you want to remove these items?**
15. Wait > See app crashed

### Expected behaviour

No App crashing

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: v5.1.1
- Tablet model: Samsung Tablet Galaxy Tab A (SM-T515)
- OS version: Android 9

### Additional context

See video:
https://www.dropbox.com/s/x2wzelbyld2vtcc/video_2020-08-14_18-13-44.mp4?dl=0

**Comment by wlthomson** [comment] 2020-08-15 06:26
Confirmed can replicate on `v5.1.2-rc1`. 

Bumping this to `v5.1.2` for now, possibly will go into `v5.1.3` (if `v5.1.2` gets released sooner).

**Comment by wlthomson** [comment] 2020-08-15 11:42
After investigating a bit more, I think the replication steps might include some unneeded things.

I can replicate this with the following simplified steps (@bijaySussol can you confirm this works for you?):

1. Create and confirm a new stocktake with one or more items. 
2. Back navigate to the stocktake page.
3. Delete the stocktake that was just created.
4. See error.

I reset and wiped data after replicating using the original steps, and this still worked for me. It seems to only occur if the stocktake which is deleted is whichever was last edited. 

@joshxg Possible theory could be the stocktake page object in the navigation state or the `StocktakeManagePage`? Any thoughts?

**Comment by joshxg** [comment] 2020-08-15 11:46
@wlthomson yeah seems like stale state - the stocktake navigation is pretty hunchy funchy, it would definitely be the first thing I would look at: Navigating `back` from `StocktakeEditPage` I think can go back to `StocktakeManagePage` or `StocktakesPage`, which means the state should be cleared differently from those cases. I don't remember the exact implementation, though

**Comment by wlthomson** [comment] 2020-08-16 11:42
@joshxg After a lot of dead ends (turns out logging objects with nested invalid realm objects causes errors that don't occur otherwise!),I think the problem is cased by the deleted stocktake record being maintained in `finalise.finaliseItem`. 

#3101 fixes the error for me, but would be good to get confirmation from @bijaySussol!

**Comment by bijaySussol** [comment] 2020-08-17 05:05
> #3101 fixes the error for me, but would be good to get confirmation from @bijaySussol!

@wlthomson Will do a quick test on my emulator thanks

**Comment by joshxg** [comment] 2020-09-21 10:08
Closed by #3101

**Closed by joshxg** 2020-09-21 10:08 UTC
Labels: 5.1.1
