### ISSUE TITLE
Lines missing from CI when created new customer requisition

### ISSUE THREAD

**Issue by nisha-dangol** [openmsupply/mobile#4562] opened 2022-01-20 12:05 UTC
## Describe the bug

A clear and concise description of what the bug is. Use screenshots!

### To reproduce
Steps to reproduce the behaviour:
In sync set-up with program settings
1. IN mobile store, Go to customer requisitions
2. Add a name(with program settings)
3. Enter other details like order type and periods
4. Add some lines and finalise.
5. See that CI is created but with no lines
Requisition created with lines:
![Screenshot_2022-01-20-15-03-58-340](https://user-images.githubusercontent.com/59193490/150335628-5a461643-f96c-4e44-a456-01e83fa365ea.jpeg)

Corresponding CI is missing the lines
![Screenshot_2022-01-20-17-55-51-687](https://user-images.githubusercontent.com/59193490/150336737-fd8fb8c8-bcaa-4f07-9636-182c253377a0.jpeg)

### Expected behaviour
CI should have lines

### Proposed Solution
Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info
- App version: msupply 506
- Tablet model: 8.4
- OS version:

**Comment by sworup** [comment] 2022-02-22 06:07
https://github.com/openmsupply/mobile/pull/4392#issuecomment-1047456652

**Comment by sworup** [comment] 2022-02-25 11:08
I thought this might still be blanking because we finalised a requisition without giving any quantity... but on my latest test I saw that giving item also creates blank requisition.

**Comment by sworup** [comment] 2022-02-28 08:51
On further investigation here's what I found out.

In mobile we can finalise customer requisition with all blank lines.
https://user-images.githubusercontent.com/683452/155939565-1a9272c0-a8df-4dd0-a591-7beb459367d5.mp4

### Detail

- `Customer requisition > Customer Data` has `Requested Quantity` column, which is 0 by default, whatever you put in here would determine the Customer requisition Customer data, and Supply Data lines and quantity thus finalised.
- If  `Requested Quantity` is 0, even if you add quantity to all of the lines in `Supply Data > Supply this invoice`, the Finalised requisition's `Supply Data` tab will not have the lines with 0 requested quantity, which is understandable. The created CI however, would have all the lines.
- We cannot add or delete lines from Customer requisition, however we can leave any or all of the `Customer Data>Requested Quantity` and `Supply Data > Supply this invoice` lines blank.
- Leaving all of the `Customer Data>Requested Quantity` blank would result in a blank (with no line) finalised Customer requisition which would also create a blank Finalised CI. **Note:** This is the issue mentioned above.
- Filling some or all lines of `Customer Data>Requested Quantity` but leaving all of the lines of `Supply Data > Supply this invoice` blank would result in customer requisition with lines containing ones you have filled Requested Quantity and a blank CI.

---

This is how mSupply desktop handles it.

![Screen Shot 2022-02-28 at 1 58 37 PM](https://user-images.githubusercontent.com/683452/155947889-d4da9f16-92e6-46ec-bce5-ea98f982cdd7.jpg)

![Screen Shot 2022-02-28 at 1 59 14 PM](https://user-images.githubusercontent.com/683452/155947876-af6bd535-04e8-41aa-9218-4dd513a23a5e.jpg)

- Do not allow CI creation (hence do not allow finalisation) until at least one of the Supply this invoice line has quantity.
- If supply this invoice has quantity but its corresponding customer requested column is 0, in finalised requisition the line would be there but with both customer requested and supply this invoice columns having 0 quantity. This although does not look good, prevents blank customer requisition.

---

## Conclusion:

Looking at these, I think the best solution would be:

- Disable finalisation of Customer Requisition at start, enable it if any of the `Supply Data > Supply this invoice` lines have quantity, disable it again if user sets all the lines to 0 again. Basically no finalisation until at least one of the `Supply Data > Supply this invoice` lines have quantity. This should prevent blank CI creation. I think this is better then deleting blank CI buy allowing creation of requisition that creates blank CI.

I am somewhat conflicted on blank Customer Requisition after finalisation but that does not look half as bad as blank CI. The solution would be to add lines that have no requested quantity but some supplied quantity but show 0 on both requested and supplied columns but we do not have log and invoice created tabs in mobile requisition as we do in desktop and also it is technically same as blank requisition, so I suppose a blank Customer Requisition is ok.

**Comment by katherine-sussol** [comment] 2022-03-30 21:50
Closed by #4608

**Closed by katherine-sussol** 2022-03-30 21:50 UTC
Labels: Priority: normal, Bug: production, Effort: medium, Investigation, Docs: internal, Status: Needs testing

**Comment by ArpitaSussol** [comment] 2022-04-01 06:24
Tested in V8.5.0-rc0

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [x] Create a Customer requisition, without giving any supplied quantity finalise it
- [x] You should get a model message saying you are not allowed and instructing you to add some supplied quantity.
- [x] Upon giving some supplied quantity finalisation should work as expected
