### ISSUE TITLE
TESTING: Supplier Credits

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#2336] opened 2020-02-16 20:54 UTC
# TESTING 

This is an issue for testing `SupplierCredit`s.

**Setup: **
- usesSupplierCreditModule must be enabled in Custom data for this feature to be enabled.
- For the ability to select a `TransactionCategory`, you must have a `Supplier Credit Category` which can be created in desktop [ Patient/Customer tab -> Transaction Category -> Create a Supplier Credit category -> sync ].

- Supplier credits can be created from the `CURRENT STOCK` page OR from a FINALISED SupplierInvoice.

## Current Stock Page

- [ ] With the module enabled, there is a column `RETURNS`.
- [ ] Clicking the icon in the `RETURNS` column opens a modal

### Modal

- [ ] The modal has the title "Available credits for ${item name}"
- [ ] With a `SupplierCredit` category, there is a drop down which can select a `SupplierCreditCategory`
- [ ] With no `SupplierCredit` category, there is no drop down to select a `SupplierCreditCategory`
- Displays all item batches 

#### Columns
- [ ] Expiry Date
    - [ ] Displays the correct expiry date
    - [ ]  Displays `N/A` if the date is not set
    - [ ] Sortable
    - [ ] NOT editable
- [ ] Batch name
    - [ ] Displays the correct batch name
    - [ ] sortable
    - [ ] NOT editable
- [ ] Supplier
    - [ ] Displays the correct Supplier name.
    - [ ] ALWAYS has a supplier name showing- as no batches should be listed which have no supplier
    - [ ] Sortable
    - [ ] NOT editable
- [ ] Quantity
    - [ ] Displays the quantity of each item batch
    - [ ] Sortable
    - [ ] NOT editable
- [ ] Return amount
    - [ ] Amount to return to the supplier
    - [ ] Sortable
    - [ ] editable
    - [ ] Can only enter positive integers into this cell
    - [ ] Must be < than the value in quantity

#### Button
- [ ] Confirm Button
    - [ ] Confirms and closes the modal
    - [ ] Creates a Supplier Credit and lines for each of the items which have a return amount
    - [ ] Does not create any lines or supplier credit if nothing was being returned
    - [ ] Creates the correct supplier credit and lines that are created when creating a supplier credit on desktop

## Supplier Invoice Page

- [ ] With the module enabled, the `New Item` button is `New Supplier Credit` when viewing a finalised supplier invoice
- [ ] With the module disabled the `New Item` button is `New Item` when viewing a finalised supplier invoice
- [ ] With the module enabled, the `New Item` button is `New Item` when viewing a finalised supplier credit
- [ ] Pressing the `New Supplier Credit` button opens a modal

### Modal

- [ ] The modal has the title "Supplier credit for supplier invoice ${invoice number} for ${supplier name}"
- [ ] With a `SupplierCredit` category, there is a drop down which can select a `SupplierCreditCategory`
- [ ] With no `SupplierCredit` category, there is no drop down to select a `SupplierCreditCategory`
- Displays each transaction batch which is in the supplier invoice

#### Columns
- [ ] Item code
    - [ ] Displays the correct item code
    - [ ] Sortable
    - [ ] NOT editable
- [ ] Item name
    - [ ] Displays the correct item name
    - [ ] Sortable
    - [ ] NOT editable
- [ ] Expiry Date
    - [ ] Displays the correct expiry date
    - [ ]  Displays `N/A` if the date is not set
    - [ ] Sortable
    - [ ] NOT editable
- [ ] Batch name
    - [ ] Displays the correct batch name
    - [ ] sortable
    - [ ] NOT editable
- [ ] Quantity
    - [ ] Displays the quantity of each item batch
    - [ ] Sortable
    - [ ] NOT editable
- [ ] Return amount
    - [ ] Amount to return to the supplier
    - [ ] Sortable
    - [ ] editable
    - [ ] Can only enter positive integers into this cell
    - [ ] Must be < than the value in quantity

#### Button
- [ ] Confirm Button
    - [ ] Confirms and closes the modal
    - [ ] Creates a Supplier Credit and lines for each of the items which have a return amount
    - [ ] Does not create any lines or supplier credit if nothing was being returned
    - [ ] Creates the correct supplier credit and lines that are created when creating a supplier credit on desktop

**Comment by Rebecca367** [comment] 2020-02-19 03:43
@joshxg 
It's not clear on how to set up supplier credits' environment.
Can you break down steps in more detail? BTW, I couldn't find specific documentations regarding to supplier credits function on either mobile wiki.  https://docs.msupply.foundation/en:mobile:user_guide
or msupply wiki.
http://docs.msupply.org.nz/
correct me if I am wrong.Thanks

# TESTING 

This is an issue for testing `SupplierCredit`s.

**Setup: **
- usesSupplierCreditModule must be enabled in Custom data for this feature to be enabled.
- For the ability to select a `TransactionCategory`, you must have a `Supplier Credit Category` which can be created in desktop [ Patient/Customer tab -> Transaction Category -> Create a Supplier Credit category -> sync ].

- Supplier credits can be created from the `CURRENT STOCK` page OR from a FINALISED SupplierInvoice.


## Current Stock Page

- [ ] With the module enabled, there is a column `RETURNS`.
- [ ] Clicking the icon in the `RETURNS` column opens a modal

### Modal

- [ ] The modal has the title "Available credits for ${item name}"
- [ ] With a `SupplierCredit` category, there is a drop down which can select a `SupplierCreditCategory`
- [ ] With no `SupplierCredit` category, there is no drop down to select a `SupplierCreditCategory`
- Displays all item batches 

#### Columns
- [ ] Expiry Date
    - [ ] Displays the correct expiry date
    - [ ]  Displays `N/A` if the date is not set
    - [ ] Sortable
    - [ ] NOT editable
- [ ] Batch name
    - [ ] Displays the correct batch name
    - [ ] sortable
    - [ ] NOT editable
- [ ] Supplier
    - [ ] Displays the correct Supplier name.
    - [ ] ALWAYS has a supplier name showing- as no batches should be listed which have no supplier
    - [ ] Sortable
    - [ ] NOT editable
- [ ] Quantity
    - [ ] Displays the quantity of each item batch
    - [ ] Sortable
    - [ ] NOT editable
- [ ] Return amount
    - [ ] Amount to return to the supplier
    - [ ] Sortable
    - [ ] editable
    - [ ] Can only enter positive integers into this cell
    - [ ] Must be < than the value in quantity

#### Button
- [ ] Confirm Button
    - [ ] Confirms and closes the modal
    - [ ] Creates a Supplier Credit and lines for each of the items which have a return amount
    - [ ] Does not create any lines or supplier credit if nothing was being returned
    - [ ] Creates the correct supplier credit and lines that are created when creating a supplier credit on desktop

## Supplier Invoice Page

- [ ] With the module enabled, the `New Item` button is `New Supplier Credit` when viewing a finalised supplier invoice
- [ ] With the module disabled the `New Item` button is `New Item` when viewing a finalised supplier invoice
- [ ] With the module enabled, the `New Item` button is `New Item` when viewing a finalised supplier credit
- [ ] Pressing the `New Supplier Credit` button opens a modal

### Modal

- [ ] The modal has the title "Supplier credit for supplier invoice ${invoice number} for ${supplier name}"
- [ ] With a `SupplierCredit` category, there is a drop down which can select a `SupplierCreditCategory`
- [ ] With no `SupplierCredit` category, there is no drop down to select a `SupplierCreditCategory`
- Displays each transaction batch which is in the supplier invoice

#### Columns
- [ ] Item code
    - [ ] Displays the correct item code
    - [ ] Sortable
    - [ ] NOT editable
- [ ] Item name
    - [ ] Displays the correct item name
    - [ ] Sortable
    - [ ] NOT editable
- [ ] Expiry Date
    - [ ] Displays the correct expiry date
    - [ ]  Displays `N/A` if the date is not set
    - [ ] Sortable
    - [ ] NOT editable
- [ ] Batch name
    - [ ] Displays the correct batch name
    - [ ] sortable
    - [ ] NOT editable
- [ ] Quantity
    - [ ] Displays the quantity of each item batch
    - [ ] Sortable
    - [ ] NOT editable
- [ ] Return amount
    - [ ] Amount to return to the supplier
    - [ ] Sortable
    - [ ] editable
    - [ ] Can only enter positive integers into this cell
    - [ ] Must be < than the value in quantity

#### Button
- [ ] Confirm Button
    - [ ] Confirms and closes the modal
    - [ ] Creates a Supplier Credit and lines for each of the items which have a return amount
    - [ ] Does not create any lines or supplier credit if nothing was being returned
    - [ ] Creates the correct supplier credit and lines that are created when creating a supplier credit on desktop

**Comment by joshxg** [comment] 2020-02-19 03:46
You're right - I need to write documentation for this.

https://docs.msupply.foundation/en:mobile:setup:server_side:config
To set up: Add `useSupplierCreditModule` to your stores custom data which will enable supplier credits. You can then create a supplier credit from a finalised supplier invoice, or through the current stock page.

**Comment by Rebecca367** [comment] 2020-02-19 20:32
@joshxg @craigdrown 

To set up: Add useSupplierCreditModule to your stores custom data which will enable supplier credits. You can then create a supplier credit from a finalised supplier invoice, or through the current stock page.
Can you guide on how to enable SupplierCreditModule in Custom data @joshxg ? 
BTW, there are no icons to return stock on CURRENT CTOCK page probably need to clarify it on how to test in on test cases? What do you think?

**Comment by ArpitaSussol** [comment] 2020-03-05 11:00
Tested in 4.0.0

# TESTING 

This is an issue for testing `SupplierCredit`s.

**Setup: **
- usesSupplierCreditModule must be enabled in Custom data for this feature to be enabled.
- For the ability to select a `TransactionCategory`, you must have a `Supplier Credit Category` which can be created in desktop [ Patient/Customer tab -> Transaction Category -> Create a Supplier Credit category -> sync ].

- Supplier credits can be created from the `CURRENT STOCK` page OR from a FINALISED SupplierInvoice.


## Current Stock Page

- [ ] With the module enabled, there is a column `RETURNS`.
- [ ] Clicking the icon in the `RETURNS` column opens a modal

### Modal

- [ ] The modal has the title "Available credits for ${item name}"
- [ ] With a `SupplierCredit` category, there is a drop down which can select a `SupplierCreditCategory`
- [ ] With no `SupplierCredit` category, there is no drop down to select a `SupplierCreditCategory`
- Displays all item batches 

#### Columns
- [ ] Expiry Date
    - [ ] Displays the correct expiry date
    - [ ]  Displays `N/A` if the date is not set
    - [ ] Sortable
    - [ ] NOT editable
- [ ] Batch name
    - [ ] Displays the correct batch name
    - [ ] sortable
    - [ ] NOT editable
- [ ] Supplier
    - [ ] Displays the correct Supplier name.
    - [ ] ALWAYS has a supplier name showing- as no batches should be listed which have no supplier
    - [ ] Sortable
    - [ ] NOT editable
- [ ] Quantity
    - [ ] Displays the quantity of each item batch
    - [ ] Sortable
    - [ ] NOT editable
- [ ] Return amount
    - [ ] Amount to return to the supplier
    - [ ] Sortable
    - [ ] editable
    - [ ] Can only enter positive integers into this cell
    - [ ] Must be < than the value in quantity

#### Button
- [ ] Confirm Button
    - [ ] Confirms and closes the modal
    - [ ] Creates a Supplier Credit and lines for each of the items which have a return amount
    - [ ] Does not create any lines or supplier credit if nothing was being returned
    - [ ] Creates the correct supplier credit and lines that are created when creating a supplier credit on desktop

## Supplier Invoice Page

- [ ] With the module enabled, the `New Item` button is `New Supplier Credit` when viewing a finalised supplier invoice
- [ ] With the module disabled the `New Item` button is `New Item` when viewing a finalised supplier invoice
- [ ] With the module enabled, the `New Item` button is `New Item` when viewing a finalised supplier credit
- [ ] Pressing the `New Supplier Credit` button opens a modal

### Modal

- [ ] The modal has the title "Supplier credit for supplier invoice ${invoice number} for ${supplier name}"
- [ ] With a `SupplierCredit` category, there is a drop down which can select a `SupplierCreditCategory`
- [ ] With no `SupplierCredit` category, there is no drop down to select a `SupplierCreditCategory`
- Displays each transaction batch which is in the supplier invoice

#### Columns
- [ ] Item code
    - [ ] Displays the correct item code
    - [ ] Sortable
    - [ ] NOT editable
- [ ] Item name
    - [ ] Displays the correct item name
    - [ ] Sortable
    - [ ] NOT editable
- [ ] Expiry Date
    - [ ] Displays the correct expiry date
    - [ ]  Displays `N/A` if the date is not set
    - [ ] Sortable
    - [ ] NOT editable
- [ ] Batch name
    - [ ] Displays the correct batch name
    - [ ] sortable
    - [ ] NOT editable
- [ ] Quantity
    - [ ] Displays the quantity of each item batch
    - [ ] Sortable
    - [ ] NOT editable
- [ ] Return amount
    - [ ] Amount to return to the supplier
    - [ ] Sortable
    - [ ] editable
    - [ ] Can only enter positive integers into this cell
    - [ ] Must be < than the value in quantity

#### Button
- [ ] Confirm Button
    - [ ] Confirms and closes the modal
    - [ ] Creates a Supplier Credit and lines for each of the items which have a return amount
    - [ ] Does not create any lines or supplier credit if nothing was being returned
    - [ ] Creates the correct supplier credit and lines that are created when creating a supplier credit on desktop

**Comment by wlthomson** [comment] 2020-04-21 08:32
@joshxg I don't believe any changes have been made to this functionality recently (correct if wrong)? If that's the case, I think this can be directly recycled for `v5.0.0`?

**Comment by joshxg** [comment] 2020-04-21 08:38
You're right - I lean more towards a "why not" approach for testing before a release, though hehe!

**Comment by wlthomson** [comment] 2020-04-21 08:39
Sorry, I didn't explain well! I meant to say I think we can directly reuse the template (not the tests).

**Comment by joshxg** [comment] 2020-04-21 08:41
oh nah I think I read what I wanted to read hehe. Yup you're right - reused it up!

**Comment by alainsussol** [comment] 2020-04-23 17:01
# TESTING 

This is an issue for testing `SupplierCredit`s.

**Setup: **
- usesSupplierCreditModule must be enabled in Custom data for this feature to be enabled.
- For the ability to select a `TransactionCategory`, you must have a `Supplier Credit Category` which can be created in desktop [ Patient/Customer tab -> Transaction Category -> Create a Supplier Credit category -> sync ].

- Supplier credits can be created from the `CURRENT STOCK` page OR from a FINALISED SupplierInvoice.


## Current Stock Page

- [ ] With the module enabled, there is a column `RETURNS`.
- [ ] Clicking the icon in the `RETURNS` column opens a modal

### Modal

- [ ] The modal has the title "Available credits for ${item name}"
- [ ] With a `SupplierCredit` category, there is a drop down which can select a `SupplierCreditCategory`
- [ ] With no `SupplierCredit` category, there is no drop down to select a `SupplierCreditCategory`
- Displays all item batches 

#### Columns
- [ ] Expiry Date
    - [ ] Displays the correct expiry date
    - [ ]  Displays `N/A` if the date is not set
    - [ ] Sortable
    - [ ] NOT editable
- [ ] Batch name
    - [ ] Displays the correct batch name
    - [ ] sortable
    - [ ] NOT editable
- [ ] Supplier
    - [ ] Displays the correct Supplier name.
    - [ ] ALWAYS has a supplier name showing- as no batches should be listed which have no supplier
    - [ ] Sortable
    - [ ] NOT editable
- [ ] Quantity
    - [ ] Displays the quantity of each item batch
    - [ ] Sortable
    - [ ] NOT editable
- [ ] Return amount
    - [ ] Amount to return to the supplier
    - [ ] Sortable
    - [ ] editable
    - [ ] Can only enter positive integers into this cell
    - [ ] Must be < than the value in quantity

#### Button
- [ ] Confirm Button
    - [ ] Confirms and closes the modal
    - [ ] Creates a Supplier Credit and lines for each of the items which have a return amount
    - [ ] Does not create any lines or supplier credit if nothing was being returned
    - [ ] Creates the correct supplier credit and lines that are created when creating a supplier credit on desktop

## Supplier Invoice Page

- [ ] With the module enabled, the `New Item` button is `New Supplier Credit` when viewing a finalised supplier invoice
- [ ] With the module disabled the `New Item` button is `New Item` when viewing a finalised supplier invoice
- [ ] With the module enabled, the `New Item` button is `New Item` when viewing a finalised supplier credit
- [ ] Pressing the `New Supplier Credit` button opens a modal

### Modal

- [ ] The modal has the title "Supplier credit for supplier invoice ${invoice number} for ${supplier name}"
- [ ] With a `SupplierCredit` category, there is a drop down which can select a `SupplierCreditCategory`
- [ ] With no `SupplierCredit` category, there is no drop down to select a `SupplierCreditCategory`
- Displays each transaction batch which is in the supplier invoice

#### Columns
- [ ] Item code
    - [ ] Displays the correct item code
    - [ ] Sortable
    - [ ] NOT editable
- [ ] Item name
    - [ ] Displays the correct item name
    - [ ] Sortable
    - [ ] NOT editable
- [ ] Expiry Date
    - [ ] Displays the correct expiry date
    - [ ]  Displays `N/A` if the date is not set
    - [ ] Sortable
    - [ ] NOT editable
- [ ] Batch name
    - [ ] Displays the correct batch name
    - [ ] sortable
    - [ ] NOT editable
- [ ] Quantity
    - [ ] Displays the quantity of each item batch
    - [ ] Sortable
    - [ ] NOT editable
- [ ] Return amount
    - [ ] Amount to return to the supplier
    - [ ] Sortable
    - [ ] editable
    - [ ] Can only enter positive integers into this cell
    - [ ] Must be < than the value in quantity

#### Button
- [ ] Confirm Button
    - [ ] Confirms and closes the modal
    - [ ] Creates a Supplier Credit and lines for each of the items which have a return amount
    - [ ] Does not create any lines or supplier credit if nothing was being returned
    - [ ] Creates the correct supplier credit and lines that are created when creating a supplier credit on desktop

**Comment by alainsussol** [comment] 2020-04-23 22:01
@joshxg @wlthomson @andreievg 

Will ask Adrian tomorrow to confirm. From what I can see, the transactions categories are for a datafile rather than being tied to a store. So  if I change it for a store then the changes are synced to that store and all other stores & mobile sites. I am assuming that this is normal but putting it out there to make sure.

**Comment by joshxg** [comment] 2020-04-23 22:06
@alainsussol 
 
Just want to make sure I understand you correctly, since there are some things here which are a little foreign for me, i.e. master transaction categories n me being stupid and stuff.

This is what I understand you are saying- when on desktop, when you edit a transaction category here:

<img width="893" alt="image" src="https://user-images.githubusercontent.com/35858975/80154058-ec499500-8612-11ea-8b60-13539a0a44c9.png">

and save it again

<img width="532" alt="image" src="https://user-images.githubusercontent.com/35858975/80154104-071c0980-8613-11ea-82c2-81e19f3f4598.png">

it is synced to all stores, not a specific store?

**Comment by alainsussol** [comment] 2020-04-23 22:14
Yes. To be completely honest, I didn't check all stores but I did a change in a different store than the one I was testing on Mobile and when I did a Manual sync it synced to the mobile store I was testing. I checked different stores on desktop and the change was visible in all the ones I checked.

**Comment by joshxg** [comment] 2020-04-23 22:16
Sweet. I'm quite sure this is the intended behaviour - since `transaction_category` is here in the system data category of the sync lookup https://github.com/sussol/msupply/blob/a29bb5433e72f82ddac4d90cb5afd3f76dde9576/vc_methods/tableSetupLookupData.txt#L247

**Comment by alainsussol** [comment] 2020-04-23 22:18
Great :)  thanks !!!

**Comment by wlthomson** [comment] 2020-04-23 22:43
@alainsussol @joshxg Yeah, [`transaction_category` is system data](https://docs.msupply.org.nz/other_stuff:remote_sync?s[]=system&s[]=data#system_vs_store-specific_data), so I think this is intended behaviour.

**Comment by alainsussol** [comment] 2020-04-24 18:24
@joshxg @wlthomson 
Hi, 
just a question when a supplier credit is created the value of the credit received of a line is not displayed on the Mobile. It is displayed on Desktop. I assume that this is intended but then, is there a way for the user to know the amount of credit he has ?

**Comment by wlthomson** [comment] 2020-04-28 02:21
@alainsussol Hm, could be wrong but this doesn't sound like intended behaviour, could you attach a screenshot?

Re. amount of credit, there's no way of viewing that currently (see #2789).

**Comment by alainsussol** [comment] 2020-04-28 13:27
Hi @wlthomson 

Here is the screenshots:

This is an invoice created in Mobile following the return of stock. There is no columns that display the monetary value of the quantity you sent back 

![image](https://user-images.githubusercontent.com/11624516/80491876-47d89300-8931-11ea-8e5d-b614031482b6.png)

Same invoice in desktop

![image](https://user-images.githubusercontent.com/11624516/80492680-612e0f00-8932-11ea-96ab-aed21ad78b55.png)

Maybe it's linked to #2789 as you say

**Comment by wlthomson** [comment] 2020-04-29 02:18
I think two different issues here:

1. You can't view the total patient credit (confirmed issue, see #2789)
2. You can't see the price details in supplier invoice.

Re. the latter, do you have payments enabled in preferences (Desktop -> Special -> Stores -> Preferences -> `"Uses payment module"`)?

**Comment by alainsussol** [comment] 2020-04-29 18:16
@wlthomson 

> Re. the latter, do you have payments enabled in preferences (Desktop -> Special -> Stores -> Preferences -> "Uses payment module")?

No I haven't but I did this morning and I have the same result. I re-initialize the app to make sure that the new store pref will be taken into account.

**Comment by wlthomson** [comment] 2020-04-30 04:06
@alainsussol Did you do a second manual sync? There's an existing bug where modules aren't updated on initial logon and require a push of the sync button. 

From current `develop`:

**Comment by wlthomson** [comment] 2020-05-06 06:30
Going to go ahead and close this out. @alainsussol if the bug still occurs, feel free to make a new issue!

**Comment by joshxg** [comment] 2021-03-11 10:11
# TESTING 

This is an issue for testing `SupplierCredit`s.

**Setup: **
- usesSupplierCreditModule must be enabled in Custom data for this feature to be enabled.
- For the ability to select a `TransactionCategory`, you must have a `Supplier Credit Category` which can be created in desktop [ Patient/Customer tab -> Transaction Category -> Create a Supplier Credit category -> sync ].

- Supplier credits can be created from the `CURRENT STOCK` page OR from a FINALISED SupplierInvoice.


## Current Stock Page

- [x] With the module enabled, there is a column `RETURNS`.
- [x] Clicking the icon in the `RETURNS` column opens a modal

### Modal

- [x] The modal has the title "Available credits for ${item name}"
- [x] With a `SupplierCredit` category, there is a drop down which can select a `SupplierCreditCategory`
- [x] With no `SupplierCredit` category, there is no drop down to select a `SupplierCreditCategory`
- Displays all item batches 

#### Columns
- [x] Expiry Date
    - [x] Displays the correct expiry date
    - [x]  Displays `N/A` if the date is not set
    - [x] Sortable
    - [x] NOT editable
- [x] Batch name
    - [x] Displays the correct batch name
    - [x] sortable
    - [x] NOT editable
- [x] Supplier
    - [x] Displays the correct Supplier name.
    - [x] ALWAYS has a supplier name showing- as no batches should be listed which have no supplier
    - [x] Sortable
    - [x] NOT editable
- [x] Quantity
    - [x] Displays the quantity of each item batch
    - [x] Sortable
    - [x] NOT editable
- [x] Return amount
    - [x] Amount to return to the supplier
    - [x] Sortable
    - [x] editable
    - [x] Can only enter positive integers into this cell
    - [x] Must be < than the value in quantity

#### Button
- [x] Confirm Button
    - [x] Confirms and closes the modal
    - [x] Creates a Supplier Credit and lines for each of the items which have a return amount
    - [x] Does not create any lines or supplier credit if nothing was being returned
    - [x] Creates the correct supplier credit and lines that are created when creating a supplier credit on desktop

## Supplier Invoice Page

- [x] With the module enabled, the `New Item` button is `New Supplier Credit` when viewing a finalised supplier invoice
- [x] With the module disabled the `New Item` button is `New Item` when viewing a finalised supplier invoice
- [x] With the module enabled, the `New Item` button is `New Item` when viewing a finalised supplier credit
- [x] Pressing the `New Supplier Credit` button opens a modal

### Modal

- [x] The modal has the title "Supplier credit for supplier invoice ${invoice number} for ${supplier name}"
- [x] With a `SupplierCredit` category, there is a drop down which can select a `SupplierCreditCategory`
- [x] With no `SupplierCredit` category, there is no drop down to select a `SupplierCreditCategory`
- Displays each transaction batch which is in the supplier invoice

#### Columns
- [x] Item code
    - [x] Displays the correct item code
    - [x] Sortable
    - [x] NOT editable
- [x] Item name
    - [x] Displays the correct item name
    - [x] Sortable
    - [x] NOT editable
- [x] Expiry Date
    - [x] Displays the correct expiry date
    - [x]  Displays `N/A` if the date is not set
    - [x] Sortable
    - [x] NOT editable
- [x] Batch name
    - [x] Displays the correct batch name
    - [x] sortable
    - [x] NOT editable
- [x] Quantity
    - [x] Displays the quantity of each item batch
    - [x] Sortable
    - [x] NOT editable
- [x] Return amount
    - [x] Amount to return to the supplier
    - [x] Sortable
    - [x] editable
    - [x] Can only enter positive integers into this cell
    - [x] Must be < than the value in quantity

#### Button
- [x] Confirm Button
    - [x] Confirms and closes the modal
    - [x] Creates a Supplier Credit and lines for each of the items which have a return amount
    - [x] Does not create any lines or supplier credit if nothing was being returned
    - [x] Creates the correct supplier credit and lines that are created when creating a supplier credit on desktop

**Closed** 2021-03-11 10:16 UTC
Labels: Build test: failure, Test Plan Template
