### ISSUE TITLE
Incorrect customer name for CR with Indicators

### ISSUE THREAD

**Issue by diegoevangelisti** [openmsupply/mobile#1976] opened 2020-01-21 04:18 UTC
## Describe the bug

New customer requisitions coming from an Internal Order (desktop) with Indicators are not getting the proper customer name. See all of them have `placeholderName`.

![Screen Shot 2020-01-21 at 5 09 03 PM](https://user-images.githubusercontent.com/32987464/72774805-c9ed5780-3c70-11ea-8fe3-da4e8afde680.png)

### To reproduce

1. Create a new `HIV program` type Internal Order related with the mobile store. 
3. Finalise the IO 
4. Sync in mobile
5. Go to Customer Requisitions
6. See error

### Expected behaviour

The proper name of the store  should be the Customer name.

### Version and device info

- App version: v3.2.0-rc3
- Tablet model: AVD
- OS version:Android 9.1

**Comment by wlthomson** [comment] 2020-01-21 21:16
It looks like the customer store `Name` record isn't getting synced from desktop. AFAIK, `[name]` records are system data so should be syncing everywhere. @andreievg @joshxg have there been any desktop side changes to `[name]` syncing related to dispensing etc?

**Comment by wlthomson** [comment] 2020-01-21 21:17
Update:

Moving to general project board as issue is unrelated to indicators.

**Comment by joshxg** [comment] 2020-02-27 18:31
@diegoevangelisti @wlthomson 

Oops I missed this.

Did you set visibility for the `name` after mobile initialization and then create the internal order?

**Comment by diegoevangelisti** [comment] 2020-02-27 23:05
> Did you set visibility for the `name` after mobile initialization and then create the internal order?

@joshxg 
No, I didn't (not sure about @wlthomson). I just followed the test cases and that happened. Happy to test it again to see if what you mentioned can be the solution to this problem

**Comment by joshxg** [comment] 2020-02-27 23:07
@diegoevangelisti 

This can wait till Monday, however I *believe* what might be the problem is just not having the `name` records synced - if they're not syncing, that means there is some visibility issue - maybe in your data file the customer is not visible, and that's why it isn't showing (But this would mean a desktop issue, I think!)

Again - lets look at this on Monday!! 👍

**Comment by diegoevangelisti** [comment] 2020-02-27 23:22
Sure, Monday it is!

**Closed** 2020-11-20 11:03 UTC
Labels: Bug: development, Docs: not needed, Effort: small, Module: indicators, Priority: high
