### ISSUE TITLE
Wanted language doesn't show on menu page when it's been changed from log-in page 

### ISSUE THREAD

**Issue by Rebecca367** [openmsupply/mobile#2553] opened 2020-03-16 22:53 UTC
## Describe the bug

Language doesn't reflect on menu page when it's been changed from log-in page 
![language change doesn't show on menu page](https://user-images.githubusercontent.com/57238075/76805828-c7f4de80-6844-11ea-9636-a07065196d85.gif)

### To reproduce

1. Go to 'log-in' page
2. Click on 'language' button to change to different language
3. Log-in

### Expected behaviour

Menu page should change its own language accordingly

### Version and device info

- App version: v4.0.1
- Tablet model: emulator
- OS version:

**Comment by wlthomson** [comment] 2020-03-26 05:16
Looks like you're trying to use Portuguese? Portuguese language support is part of `v5.0.0` release (try replicate this on `develop`). 

See https://github.com/openmsupply/mobile/issues/2445.

Going to go ahead and close as a duplicate of #2115. Can reopen if problem still occurs.

**Comment by Rebecca367** [comment] 2020-03-26 05:23
@wlthomson 
This issue is definitely a bug that something hasn't come though unless it's planned. There is Portuguese on language selection after it's been selected menu page shows in English and once you click on any of buttons, it shows Portuguese again. It's tested in dev.

**Comment by joshxg** [comment] 2020-03-27 07:26
Have tried to reproduce this and am unable to! If we get some repro steps which someone else can replicate then we can have another look at this!

**Comment by wlthomson** [comment] 2020-03-31 23:56
I still can't repro, so I'm guessing this may have been a mistake (possibly running the wrong version)? 

@Rebecca367 If you're still around and want to provide some steps for replicating on `develop`, I'll leave this open until the end of this week.

**Closed** 2020-11-20 09:10 UTC
Labels: API: sync, Bug: development, Docs: not needed, Effort: small, Good first issue, Needs testing, Priority: high
