### ISSUE TITLE
Sync to have logging

### ISSUE THREAD

**Issue by andreievg** [openmsupply/mobile#1025] opened 2019-06-19 23:45 UTC
## Describe the feature

Some remote sites have sync issues, most are in the form of 'Server rejected sync record'. We need more fine grained information to diagnose these issues, should bug snag sent record/s and response message from the server.

Somewhere here:
https://github.com/openmsupply/mobile/blob/8af51fb96230857923d30c0b7a10f3b46756ae20/src/sync/Synchroniser.js#L278-L284

**Comment by mark-prins** [comment] 2019-06-20 02:26
That sounds sensible. 
I'm curious - the `responseJson.error` would be returned by our server, wouldn't it? If so, is that logged? Could there be a UUID or similar to tie the events together? Then we can match entries of 'Server rejected..' to the log entry on the server.

**Comment by andreievg** [comment] 2019-06-20 02:38
> I'm curious - the responseJson.error would be returned by our server, wouldn't it

That would be logged by proposed changes yeah, currently that fine information is ignored.

> Could there be a UUID or similar to tie the events together? Then we can match entries of 'Server rejected..' to the log entry on the server.

To be honest, it's pretty hard for me to go through every possible error and see if it's logged or not. It doesn't look like the server provides any UUID's though when returning an erroneous response.

The idea was, log the error, and log the full post body/url, so that we can replicate it locally (post the same data via postman to local copy of server's data file)

**Comment by Chris-Petty** [comment] 2019-06-20 04:52
Duplicate of #680

**Comment by andreievg** [comment] 2019-06-21 02:02
@Chris-Petty i also thought that this is a duplicated, but couldn't find the issue (was searching for sync in the title, bring back brackets : ) [sync][logging]

**Comment by andreievg** [comment] 2019-06-21 02:21
I ma take this one on.

Just for reference, we have 5 fetches in 'Synchroniser.js' + one call to 'authenticate' (fetch call there is too deep to chase/modify)

The 5 fetches don't have uniform error handling, some check for `(response.status < 200 || response.status >= 300)` some don't. Some don't wrap await response.json() in try catches, etc..

It seems a uniform solution makes sense -> make a wrapper around fetch to unify error handling and add bugs-snag notification.

**Comment by raviSussol** [comment] 2019-06-24 10:52
@andreievg I also think that the error should also be logged in the server. So that it helps to quick check what has gone wrong with the pushing record. https://github.com/sussol/msupply/issues/3636

**Comment by Chris-Petty** [comment] 2019-06-24 11:22
@raviSussol 100% agree. I highlighted that in a support ticket but didn't make an issue hah https://support.msupply.org.nz/cerb6/profiles/ticket/NA-8494-XK. Thanks for jumping into it!

**Comment by joshxg** [comment] 2019-07-31 04:38
Closed by #1028

**Closed** 2019-07-31 04:38 UTC
Labels: Feature, Priority: High

**Comment by joshxg** [comment] 2019-10-11 08:54
## Testing
- [x] When an error occurs during sync, a bugsnag report is sent [This should be sent in all cases where sync is being prevented]
    - [x] Where there are invalid reports on the server
    - [x] Where there are invalid reports on mobile
- [x] The bugsnag report is detailed and useful

This is also logging when a user inputs the wrong username and password. Issue #1322
