### ISSUE TITLE
After adding a New Stocktake it doesn't show up in Current list

### ISSUE THREAD

**Issue by diegoevangelisti** [openmsupply/mobile#1613] opened 2019-11-27 02:21 UTC
## Describe the bug

After adding a New Stocktake, it doesn't show up in the Stocktake Current list right after coming back to previous page.

![new-stocktake-doesnt-show-up](https://user-images.githubusercontent.com/32987464/69687282-3fccbb00-1127-11ea-9963-393433ce56fd.gif)

### To reproduce

Steps to reproduce the behaviour:

1. Add a New Stocktake
2. Back to previous page (Stocktake)

### Expected behaviour

Any created New Stocktake should appear on the Current list right after the user goes back to Stocktake page.

### Version and device info

- App version: v3.0.4
- Tablet model: Lenovo TB-X304L
- OS version: Android 8.1.0

Also tested on Android Emulator (Name: WXGA API 28, OS version: Android 9.0)

**Comment by joshxg** [comment] 2019-11-27 02:30
At a guess this looks like a regression from my pr here: https://github.com/openmsupply/mobile/pull/1581 -- where I changed code in `useNavigationFocus` custom hook.

I will pick this up and make sure

**Comment by joshxg** [comment] 2019-11-28 03:55
Closed by #1616

**Closed by joshxg** 2019-11-28 03:55 UTC
Labels: Bug: development, Docs: not needed

**Comment by Rebecca367** [comment] 2019-12-02 22:24
Testing was carried out on emulator. All good.

# TESTING

### Table

#### NOTE: LINES IN THIS TABLE ARE BY BATCH - NOT ITEM

#### Row Press
- [x] Pressing on a row has no effect
    
#### Filtering
- [x] Batches are filtered by Item Name
- [x] Filtering is cleared when the search term is cleared.

- [x] **Remove**
    - [x] Column NOT sortable
    - [x] Cells NOT editable
    - [x] Can select any row
    - [x] Can select multiple rows
    - [x] Selecting a row opens a confirmation dialog at the bottom of the page.
    - [x] Unselecting a row closes the confirmation dialog at the bottom of the page.
    - [x] Confirming the confirmation dialog deletes the batches    
    - [x] Cancelling the confirmation dialog removes the current selection and closes the confirmation dialog
    - [x] Is DISABLED when finalised

### Buttons
- [x] Clicking New line button opens a "select an item" dialog

### Page Info
- [x] **Entry Date**
    - [x] Shows the correct entry date for this invoice
- [x] **Confirm Date**
    - [x] Shows the correct date for confirming this invoice (confirming an SI on mobile === finalising)
- [x] **Entered By**
    - [x] Shows the correct user who created the invoice
- [x] **Supplier**
    - [ ] Shows the correct supplier this invoice is for.
- [x] **Their Ref**
    - [x] Displays the Their Ref field for this invoice correctly
    - [x] Clicking opens a Their ref modal (see modals)
    - [x] Is disabled when finalised.
- [x] **Comment**
    - [x] Displays the Comment field for this invoice correctly 
    - [x] Clicking opens the comment modal (see modals) 
    - [x] Is disabled when finalised.

### Modals
- [x] **New Line**
    - [x] Title is `Search for an Item to add`
    - [x] Options to select ALL/ANY Item.
    - [x] Search Bar is auto focused on opening
    - [x] Closing the modal, closes the modal
    - [x] Clearing the search term clears filtering
    - [x] Right hand side column of the list of options lists the correct available quantity
- [x] **Comment**
    - [x] Title is `Enter the invoice comment
    - [x] Empty if no comment
    - [x] Entering a comment and pressing OK saves the comment correctly
    - [x] closing the modal closes the modal
- [x] **Their ref**
    - [x] Title is `Enter their reference`
    - [x] If there is already their reference, it is entered already.
    - [x] Empty if no their reference
    - [x] Entering a their reference and pressing OK saves their reference correctly
    - [x] closing the modal closes the modal

### Finalizing
- [x] Pressing finalize opens a confirmation dialog warning about locking the invoice
- [x] Cancelling the confirmation cancels finalizing the invoice
- [x] Confirming the confirmation dialog finalises the invoice, locking all edits (as listed above)
- [x] Finalizing the invoice correctly sets the status of the invoice to finalised.
- [x] All 0 quantity items are pruned from the invoice - leaving only items with an actual quantity entered.

**Comment by Rebecca367** [comment] 2019-12-02 22:25
noted! thanks and will move this item to done.

**Comment by joshxg** [comment] 2019-12-02 23:28
@Rebecca367 have you commented in the wrong issue?
