### ISSUE TITLE
Sorting by name does not seem to work

### ISSUE THREAD

**Issue by nisha-dangol** [openmsupply/mobile#4858] opened 2022-08-08 05:39 UTC
## Describe the bug
In Dispensing, sorting does not seem to work by first or last name, while it is working well when sorted by DoB

### To reproduce
Steps to reproduce the behaviour:
1. In Dispensing, create a new patient with let's say both first & last name starting with `A`
2. Now in that list of patients, sort by first name and last name and see if that patient appears in the sorted order.
3. See error
4. Now try sorting with DoB and see that created patient appears in sorted order.

### Expected behaviour
Sorting should work by first and last name properly

### Proposed Solution
Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info
- App version: latest apk built [here](http://t.ly/K3Xv)

**Comment by sworup** [comment] 2022-08-26 06:59
Ok the sorting is working, but you are seeing field values with spaces at top, that is confusing you. It is a annoying issue, the names should have been trimmed to remove extra spaces at the start and end but the problem is not a deal breaker.

Sorting however is working so I am closing this issue.

**Closed by sworup** 2022-08-26 06:59 UTC
Labels: Priority: low, Bug: ????, Project: Kiribati COVID-19 Vax
