### ISSUE TITLE
App crashes when clicking on`"Use Suggested Quantity"` in a Customer Requisition

### ISSUE THREAD

**Issue by diegoevangelisti** [openmsupply/mobile#2759] opened 2020-04-23 04:26 UTC
## Describe the bug

The app crashes when working on a `"Customer Requisition"` and pressing the `"Use Suggested Quantity"` button. This is the error message retrieved after trying to reload the page:

![Screen Shot 2020-04-23 at 4 20 00 PM](https://user-images.githubusercontent.com/32987464/80058887-8c091380-857e-11ea-8059-58b36250caa1.png)

Customer requisition before clicking on `"Use Suggested Quantity"`:
![Screen Shot 2020-04-23 at 4 08 49 PM](https://user-images.githubusercontent.com/32987464/80058209-c96ca180-857c-11ea-86f0-6e3c95ae8c82.png)

### To reproduce

1. Go to 'Customer Requisitions' -> Select a 'Customer Requisition'
2. Click on the button: `"Use Suggested Quantity"`.

### Expected behaviour

The app shouldn't crash and update the Supplied quantity (if necessary).

### Proposed Solution

N/A.

### Version and device info

- App version: v5.0.0-rc1
- Tablet model: AVD
- OS version: Android 9.0 API 28

### Additional context

This happened while testing #1244. (Related with issues #2758 as well)

**Comment by wlthomson** [comment] 2020-04-23 04:31
Eep.

Just to keep things a bit more managable, I think we can close this as a duplicate of #2758 and update that issue for both bugs?

**Comment by diegoevangelisti** [comment] 2020-04-23 05:01
Agreed! closing and moving now!

**Comment by diegoevangelisti** [comment] 2020-04-23 05:03
Closed. Duplicate of #2758

**Closed** 2020-04-23 05:02 UTC
Labels: Bug: development, Docs: not needed, Priority: high

**Comment by ArpitaSussol** [comment] 2020-05-06 04:14
Tested in v5.0.0-rc3 as well

## Testing

- [x] App does not crash on setting customer requisition supplied quantity to requested quantity. - **PASS**
- [x] App does not crash on setting customer requisition supplied quantity to suggested quantity. - **PASS**
