### ISSUE TITLE
Sensor: Blink icon stuck in "in progress" stage in endless loop

### ISSUE THREAD

**Issue by ArpitaSussol** [openmsupply/mobile#3628] opened 2021-02-25 09:37 UTC
## Describe the bug

After clicking blink for 2-3 times, it start behaving stuck in progress phase and keep on rotating. Even removing this sensor and adding it again results same

### To reproduce

1. Go to Vaccine -> Add new sensor
2. Click on Blink "Bulb" icon
3. Sensor will blink. Try to click that bulb icon again
4. See error. Now its goes to never ending in progress stage.

https://user-images.githubusercontent.com/58979436/109133368-0c8b3880-777d-11eb-8ff0-ab8fdedc80f9.mp4

### Expected behaviour

Blink should show warning message in case of any error. In progress stage should be halted after few seconds.

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version:
- Tablet model:
- OS version:

**Comment by wlthomson** [comment] 2021-03-02 02:24
I can't replicate this with the given steps, but I can by moving the sensor out of range. 

I think the easier solution is just to add a reasonable timeout, Although an "error" state would be nice, I don't think it's a high priority, given that this is just a mechanism for identifying the sensor.

**Comment by wlthomson** [comment] 2021-03-03 03:42
Update: timeout already exists (max retries). Looks like this is caused by missing error handling logic in the blink thunk.

**Comment by wlthomson** [comment] 2021-03-03 07:34
Fixed by #3658.

**Closed by wlthomson** 2021-03-03 07:34 UTC
Labels: Bug: development, Effort: small, Module: vaccines, Priority: normal

**Comment by ArpitaSussol** [comment] 2021-03-04 05:19
Tested in V7.0.0 rc8

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [x] Move a connected sensor out of range and "blink" it. After maximum retries have been exhausted (this can take some time), the blink animation stops and no errors are displayed.

However Blink icon keeps enabling and disabling automatically that result in wait for Blink icon to be enabled to click on it.
Created an issue #3662
