### ISSUE TITLE
A few details in the breach report are incorrect

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#3742] opened 2021-03-11 20:30 UTC
## Describe the bug

In the breach report (which is created then emailed), there are a couple of details which are incorrect:

- Breach config duration
	- this is being displayed as `20000 minutes` for a 20 minute breach
- Breach config type
	- this is not being displayed at all

### To reproduce

1. Go to your sensor, download some logs for awhile
2. Click on the download icon
3. have the report emailed to you

### Expected behaviour

The details should be accurate

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version:
- Tablet model:
- OS version:

### Additional context

![image](https://user-images.githubusercontent.com/35858975/110851095-78d97080-8315-11eb-8657-794b934cb270.png)

[12-03-2021-0926.csv.zip](https://github.com/openmsupply/mobile/files/6125807/12-03-2021-0926.csv.zip)

**Comment by katherine-sussol** [comment] 2021-03-11 23:21
Looks like just a few wrong strings/constants here and there 😆 . Also seems like the logging section is a bit off too - will also update:

![image](https://user-images.githubusercontent.com/65875762/110868413-6a974e80-832d-11eb-8873-64dc731e04af.png)

**Comment by wlthomson** [comment] 2021-03-12 03:26
Fixed by #3748.

**Closed by wlthomson** 2021-03-12 03:26 UTC
Labels: Docs: not needed, Effort: small, Priority: high

**Comment by ArpitaSussol** [comment] 2021-03-12 08:00
Tested in V7.0.0RC11

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [x] Reproduce #3742 
- [x] Check breach duration config setting is correctly reported in minutes for each config type
- [x] Check the breach types are correctly displayed
- [x] Check that the logging section displays the logging start date/time and the logging interval
