### ISSUE TITLE
Set requistion.isRemoteOrder to false by default on the mobile

### ISSUE THREAD

**Issue by ujwalSussol** [openmsupply/mobile#4387] opened 2021-08-30 09:52 UTC
Set requistion.isRemoteOrder to false by default on the mobile

It seems that the field `requistion.isRemoteOrder` is set to true on the mobile where as in the desktop remote site it is set to false.  

So `isRemoteOrder` does not really literally mean remote order as both of these desktop and mobile requisitions are remote. 

As a result converting a desktop system to a mobile system is not working smoothly :  
https://support.msupply.org.nz/cerb6/profiles/ticket/ZN-4182-LB

Further for PNG we are suddenly seeing extra columns for Requisition Response forms. 

https://support.msupply.org.nz/cerb6/profiles/ticket/12969

Now @adrianwb  pointed out that `requistion.isRemoteOrder` is used by Ivory Coast to create orders in the cloud when the remote active tablet is stolen. mSupply desktop app, supports this theory. 

## The suggestion

So the conclusion : 

- The name of the field `requistion.isRemoteOrder` is confusing and it really should be `requistion.isRemoteOrderCreatedonCloud`  [ due to compatibility options we can't chnage this now] 
- We simply get the mobile tablet to ignore this field `requistion.isRemoteOrder` and set it to false.
- Data control on the Mobile to be handle in a different way and `requistion.isRemoteOrder` should not be used.

**Why?**

This will make the Mobile and desktop data structure the same. 

## Describe alternatives you've considered

No can't think of any thing better.

## Additional context

If theses user column are asked by the user then we can add a store preference in the desktop.

**Comment by adrianwb** [comment] 2021-08-30 10:02
Agreed - I'm not aware of any reason why it should be set to `True` on mobile, and that it does need some more explanation in the comments...

**Comment by sworup** [comment] 2021-08-30 10:32
@adrianwb in mobile, the idea is that only the requisition created by mobile can edit or delete the requisition. The `remoteOrder` database field is set to true by mobile during requisition creation and only used to disable deletion of requistion (if remoteOrder is false). 

As @ujwalSussol said, it seems this field is used in mobile to represent something completely different then what it represents on desktop.

It does have its use though, don't know if requisitions on desktop should show extra columns based on requistion.isRemoteOrder that is set by mobile.

**Comment by ArpitaSussol** [comment] 2021-12-08 08:02
@katherine-sussol this issue has been fixed or not? because following testcases in PR it still showing the same behavior. 

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [ ] Open requisition list, none of the requisitions in the list should have deletion disabled now that we are disabling `isRemoteOrder` check. **FAILED**
- [ ] Create a requisition from mobile
  - [ ] Go to desktop to check, it should not have extra columns.
Can it be closed for now?

**Comment by katherine-sussol** [comment] 2021-12-08 20:21
Hi @ArpitaSussol - It looks like this one is still in PR sorry (and has been for a while - whoops), I'll follow up and see what can be done to close it out.

**Comment by ArpitaSussol** [comment] 2021-12-09 04:39
> Hi @ArpitaSussol - It looks like this one is still in PR sorry (and has been for a while - whoops), I'll follow up and see what can be done to close it out.
thanks :)

**Comment by ArpitaSussol** [comment] 2021-12-09 04:44
> Hi @ArpitaSussol - It looks like this one is still in PR sorry (and has been for a while - whoops), I'll follow up and see what can be done to close it out.

Thanks 👍 !!!

**Comment by sworup** [comment] 2022-03-02 05:14
@katherine-sussol this issue might be temporarily fixed by deleting sg requisition during desktop to mobile conversion. Hence not needing any changes in mobile code.

We quickly discovered that simply converting requistion.isRemoteOrder to false does not work as it had a lot of side effects. The original intention of the variable and the way it is being used in mobile are different, which is a design flaw... and fix it a bit of redesign should be done.

The fix in the PR and the fixes suggested by others all were not viable solution. Also, the original mobile code had bugs that I discovered while trying to do this fix so those changes need to be added to mobile master... and then we can see how this issue can be tackled.

Since, we already have a no code (mobile repo) fix and this issue although visible on desktop and mobile does not do too much harm. I think we should close this issue and PR, without merging for now. 

@ujwalSussol, what do you think sir?

**Comment by katherine-sussol** [comment] 2022-04-07 00:34
Closing as per comments. Related Desktop issue: https://github.com/sussol/msupply/issues/10490

**Closed by katherine-sussol** 2022-04-07 00:34 UTC
Labels: Refactor, Status: In progress
