### ISSUE TITLE
Stocktake reasoning: If no difference user should be allowed to finalize the stock take

### ISSUE THREAD

**Issue by anildahalsussol** [openmsupply/mobile#5039] opened 2022-12-20 10:22 UTC
## Describe the bug

Sometimes user use stock take just to change price, batch, suppliers not only quantity. So in that case, if the difference is 0 then it's not allowing to finalize the stock take.
### To reproduce

Steps to reproduce the behaviour:

1. Go to Stock take.
2. Create new.
3. Just change batch or price.
4. Finalize see error.

### Expected behaviour

If differen is N/A for all lines it should show exisitng alert and if any other lines have difference 0 then still need to allow to finalize and if the difference is higher than 0 then reason set alert must be shown incase of empty.
### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: 8.6 rc3
- Tablet model: lenovo
- OS version:

**Comment by sworup** [comment] 2023-01-06 11:06
Resolved with #5047

**Closed by sworup** 2023-01-06 11:06 UTC
Labels: Bug: development, Status: In PR

**Comment by AnushaUp** [comment] 2023-01-23 09:58
## Testing
Tester `V8.6.2-rc04`
Steps to reproduce or otherwise test the changes of this PR:

- [ ] Enable reason (positive and negative) from desktop
- [ ] Sync to mobile well
- [ ] Before testing make sure to test for different type of test case scenario as below then follow from step 4
  - It looks at only counted items, then check all batches of that items.
  - If the batch has counted and there is quantity difference then look at its valid reason.
  - If reason is not set then don't allow to finalize otherwise finalize
- [ ] Create an stocktake and set reason for some of its batch and ignore for some
- [ ] If at least one batch misses the reason then you can't finalize the stocktake
- [ ] When click the finalize button alert `The reason must be set for each item before finalizing stocktake` popped up.
- [ ] Repeat the test by disabling the reason from desktop and clicking finalize button
- [ ] If reason is disabled then one can easily finalize stocktake.
