### ISSUE TITLE
Incoming sync to integrate records with own storeID only

### ISSUE THREAD

**Issue by andreievg** [openmsupply/mobile#1062] opened 2019-07-16 22:30 UTC
## Describe the bug
In IncomingSyncUtilities, we don't check that incoming sync record is actually for current store id. This may cause issue (and already has in Ivory Coast) where site A data is transferred to site B, causing site B to integrate site A data as their own

### To reproduce 
Haven't tried, but:
1. Set up two mobile sites from one data file
2. Try making both sites collector of the other
3. Add some transactions that modify stock
4. Sync both mobiles sites
5. Should see item line info from one sites mixed with the other one

### Expected behaviour
Incoming records for foreign site should not be integrated

### Version and device info
 - 2.3.4

Implementer to list which record types need this storeID check, and as @Chris-Petty suggested, there may not be an easy solution to records like trans lines as they don't have store id, only linked transact has store id

Also as @Chris-Petty suggested, bug snag this behaviour when it happens

**Comment by joshxg** [comment] 2019-07-17 02:54
Maybe I am misunderstanding some concepts here:

I think a somewhat equivalent check should be done on the server. It would be better that records don't use any bandwidth as a first point of prevention. I think this should possibly also be done on mobile, but the server could also check that a `trans_line` is related to a `transact` which has a correct `store_ID`?

Would an additional fail safe for desktop be that only one store should be allowed a `sync_ID` that is related to a mobile store?

**Comment by Chris-Petty** [comment] 2019-07-17 23:37
@joshxg I agree that server side would be better. I was ok with this 'cause the check should be negligible overhead for item_lines and in theory the server shouldn't have ever started sending them, yet here we are. Mobile should definitely scream loudly about it if the check is ever set off.

could you make an issue on msupply repo? There would need to be some discussion to make sure it works for both mobile and desktop. My primary thought being server should check that the record belongs to at store on the sync site. This doesn't solve multiple sites being active or collector on the mobile sync site. We're not yet storing on the server what sites are mobile or desktop I think, though I believe there's an issue for it.

**Comment by adrianwb** [comment] 2019-07-30 10:28
@joshxg @Chris-Petty I think you're over-thinking this? IMHO, the simple solution is to only include item lines from the current store when displaying/amending stock,  in the same way that mobile seems to already hide transactions (and therefore their trans_lines) from any other store

**Comment by adrianwb** [comment] 2019-07-30 10:51
@andreievg Perhaps the easiest way to reproduce the problem is just to deliberately create a sync record for an item line from another store and send it to the mobile site e.g. something like:

`query([item_line];[item_line]store_id = <<other store ID>>)`
`reduce selection([item_line];1)`
`sync_generate_sync_record (Table(->[item_line]);"I";12;<<sync site ID for mobile store>>;<<mobile store ID>>) `

**Comment by joshxg** [comment] 2019-07-31 02:08
@adrianwb Possibly! I do think that mobile should have some level of defensive code to prevent this behaviour, but I thought the more important fix seems to be preventing it from happening in the first place? I guess I don't understand why mobile is being sent `item_line`, `transact` or `trans_line` records which aren't meant for that store in the first place. If it was a configuration issue it seems that preventing incorrect configurations would be the first place to start?

**Comment by andreievg** [comment] 2019-07-31 05:49
We actually still don't have a sure way to identify that a site is mobile (from primary server perspective), apart form checking if it's hitting the v3 api (but not when sync out record are put into sync queue for a particular site). Since desktop allows multiple stores on a site and mobile allows only one, quite a bit of sync logic needs to be changed, and to be honest we want to touch that bit of code as little as possible (previously we had some issues when sync code is changed and affects existing customer, this is very hard to test). I would limit the change to mobile for now, since it's the 'black sheep' of our sync ecosystem.

One thing of course that primary sync site should not be doing, is sending records to sites for stores that are not active/collector. (this still doesn't deal with use case where multiple stores are configured for one mobile sync site)

**Comment by adrianwb** [comment] 2019-07-31 13:13
> 
> 
> @adrianwb Possibly! I do think that mobile should have some level of defensive code to prevent this behaviour, but I thought the more important fix seems to be preventing it from happening in the first place? I guess I don't understand why mobile is being sent `item_line`, `transact` or `trans_line` records which aren't meant for that store in the first place. If it was a configuration issue it seems that preventing incorrect configurations would be the first place to start?

Mobile has been receiving the other halves of transactions (& their lines) and requisitions (& their lines) since the start, as that is standard behaviour (both sites get copies of both halves), and without any negative consequences as these are simply not displayed in the mobile UI (as it should be).

The problem arose when item lines from another store were unintentionally synced to mobile, and these were unknowingly included in the mobile UI, showing up in the displayed stock and in stocktakes. Somehow, mobile appears to override the item line record's _actual_ store and set it to be the mobile store instead => this is a dangerous bug and needs to be fixed.

Yes, we should try to avoid sending mobile bad data to start with, but it really should be robust enough to handle it itself!

**Comment by adrianwb** [comment] 2019-07-31 13:19
> We actually still don't have a sure way to identify that a site is mobile (from primary server perspective), apart form checking if it's hitting the v3 api (but not when sync out record are put into sync queue for a particular site). Since desktop allows multiple stores on a site and mobile allows only one, quite a bit of sync logic needs to be changed, and to be honest we want to touch that bit of code as little as possible (previously we had some issues when sync code is changed and affects existing customer, this is very hard to test). I would limit the change to mobile for now, since it's the 'black sheep' of our sync ecosystem.

Yes, it would be good to have a "proper" way to distinguish between mobile & desktop sync sites - the infrastructure is already there - it just hasn't been implemented yet...

> One thing of course that primary sync site should not be doing, is sending records to sites for stores that are not active/collector. (this still doesn't deal with use case where multiple stores are configured for one mobile sync site)

See previous comment - https://github.com/openmsupply/mobile/issues/1062#issuecomment-516843096

**Comment by Chris-Petty** [comment] 2019-07-31 23:37
@adrianwb I agree that it'll be good for mobile to handle the item_lines better. This goes back to the assumption that mobile was only ever one store and would only receive records for that store, which outside of sync misconfiguration or erroneous footrunner hasn't been a problem (or not observed/reported anyway). I don't think mobile will support multiple stores.

For this issue, the crux is this line here writing of the `store_ID` when syncing out: https://github.com/openmsupply/mobile/blob/master/src/sync/outgoingSyncUtils.js#L81

Just ignoring itemBatches/item_lines that don't belong to the mobile store on the tablet would be the easiest solution. Alternative is: 
- changing the schema to actually include store_ID
- save incoming value on incoming sync
- write to it when making new ones
- read it on outgoing sync
- filter by it in UIDatabase
- migration code to write the tablet store ID to existing itemBatches

Other than simply not touching mobile sync, this doesn't really give us anything more than just ignoring the records on incoming sync. It's basically a whole lot of work to support multiple stores, which isn't on the road map for mobile. **TL;DR:** Just block item_line records on incoming sync.

While I was looking there, I think I've spotted a more subtle bug from when only ever having one supplier was also assumed: https://github.com/openmsupply/mobile/blob/master/src/sync/outgoingSyncUtils.js#L92

This would make it look like all stock came from the same supplier (the one set on the mobile store's name record as default I think) regardless of what store/name the supplier invoice came from.

**Problems on the server are:**
- Not tracking what sites are mobile yet (right?)
- Creating sync_sites, stores and config not on rails/no validation (been on the backlog to improve for mass deployment/scalability)
- Given mobile context of low connectivity, sending records that don't need to be sent (as far as I can tell this only happens from bad configs or footrunners)

**Comment by Chris-Petty** [comment] 2019-07-31 23:54
>Mobile has been receiving the other halves of transactions (& their lines) and requisitions (& their lines) since the start, as that is standard behaviour (both sites get copies of both halves), and without any negative consequences as these are simply not displayed in the mobile UI (as it should be).
@adrianwb are you saying that if mobile makes a customer invoice, it gets a copy of the supplier invoice generated for the customer store? Cause I'm pretty sure that's not right. Likewise mobile doesn't get a copy of the customer requisition generated for a store that it did a supplier requisition to? I'd expect desktop to only do this if it had a collector copy of the other party too, right?

**Comment by joshxg** [comment] 2019-08-01 04:39
So just to get this straight, this issue should have a PR for:

- reject any `item_line`/`ItemBatch` coming from incoming sync that does not belong to the store (This is how `Transaction`/`transact` records are handled, also)

**Comment by adrianwb** [comment] 2019-08-01 08:23
> 
> 
> So just to get this straight, this issue should have a PR for:
> 
>     * reject any `item_line`/`ItemBatch` coming from incoming sync that does not belong to the store (This is how `Transaction`/`transact` records are handled, also)

Yes, I think that will solve this problem

**Comment by adrianwb** [comment] 2019-08-01 08:35
> 
> 
> > Mobile has been receiving the other halves of transactions (& their lines) and requisitions (& their lines) since the start, as that is standard behaviour (both sites get copies of both halves), and without any negative consequences as these are simply not displayed in the mobile UI (as it should be).
> 
> @adrianwb are you saying that if mobile makes a customer invoice, it gets a copy of the supplier invoice generated for the customer store? Cause I'm pretty sure that's not right. Likewise mobile doesn't get a copy of the customer requisition generated for a store that it did a supplier requisition to? I'd expect desktop to only do this if it had a collector copy of the other party too, right?

The code to generate the other half of a transfer (on the central server) has always sent both halves of the transfer to both sites. Often the other site's store is a "transfer", which is disabled to normal logins on desktop, but we can still login for diagnostic purposes to investigate issues with syncing transfers. Mobile sites will also have been receiving the other halves of transfers (and ignoring them), but that isn't really the issue here. Whether or not the server sends these records as part of the normal processes, mobile should still do enough to filter them out, otherwise there's no protection against rogue footrunner.

**Comment by joshxg** [comment] 2019-09-07 03:21
Closed by #1086

**Closed by joshxg** 2019-09-07 03:21 UTC
Labels: Bug: production, Docs: not needed, Effort: small, Priority: High

**Comment by wlthomson** [comment] 2019-10-14 03:30
## TESTS

- [x] Sync an [item_line] from desktop which has an incorrect storeID for the apps store. It doesn't get integrated.
