### ISSUE TITLE
New Stock take crashes when building Mobile from branch : release-v8.6.2

### ISSUE THREAD

**Issue by ujwalSussol** [openmsupply/mobile#5068] opened 2023-01-11 12:21 UTC
## Describe the bug

New Stock take crashes when building Mobile from branch : release-v8.6.2

@ujwalSussol  Took a Remote Kiribati Active pharmacy datafile and turned it to  a normal sync data.  Kiribati have a Mirror sync system. 

Existing Beru site was turned into a mobile site.  The Mobile site was setup, but creating a Stock take crashes.

Then a new Patan store was created.... This too showed the same behaviour. The Mobile App crashes on New stock take.

### To reproduce

Steps to reproduce the behaviour:

1. Get the Kiribati datafile modified by Ujwal :  https://drive.google.com/drive/u/0/folders/17STRhoe5IMmKpx9gygNesQejl_HorkOx
2. Get mSupply server V7-00-02  or 4d dev running.
3. Create Mobile based on Branch "release-v8.6.2"
4. Sync the store.
5. Create a stocktake
6. See Error
7. @ujwalSussol  Tried the Solomons datafile and the same issue was encountered. 

![Mobile_stocktake_error-2023-01-11-T18-05](https://user-images.githubusercontent.com/6764266/211804869-894e965c-8514-4357-a02c-cd5530bed515.png)

### Expected behaviour

Should not crash

### Proposed Solution

don't know

### Version and device info

- App version: release-v8.6.2
- Tablet model:
- OS version: V7-00-02

### Additional context

Same issue encountered on the Solomons datafile.

**Comment by sworup** [comment] 2023-01-17 08:39
This issue was introduced by code here https://github.com/openmsupply/mobile/commit/f5f3b612728adec9ccd2ec9c31ed81397933ad94.

Previously StocktaakeManagerPage was expecting an object as prop but was getting undefined and that gave this warning:

![SCR-20230117-jx9](https://user-images.githubusercontent.com/683452/212849131-3cb27faa-4922-4d86-ad4d-84be5992c16c.png)

I made the changes in the commit f5f3b612728adec9ccd2ec9c31ed81397933ad94 to fix this warning and it spawned this error because now that the default value is empty object it is no longer undefined and the methods that had undefined checks were getting called.

I fixed with by adding an checkIsObjectValuesEmpty check method instead of object cheack.

**Comment by sworup** [comment] 2023-01-19 05:11
Merged with #5070

**Closed by sworup** 2023-01-19 05:11 UTC
Labels: Effort: medium, Priority: immediate, Bug: development

**Comment by santoshkhanal12** [comment] 2023-01-24 06:16
Tested on mobile v8.6.2-rc04

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [ ] Log into mobile store
- [ ] Go into stocktakes
- [ ] Create new stocktake
- [ ] You should be able to create, edit or delete stocktake without any errors or warning **-PASS-**
