### ISSUE TITLE
Settings not showing up on Mobile even with correct permissions

### ISSUE THREAD

**Issue by npendergrast** [openmsupply/mobile#4078] opened 2021-06-03 23:23 UTC
**Describe the bug**
On the new Vanuatu vaccine server the admin users with all permissions ticked on the server still cannot see the settings option on Mobile.

**To Reproduce**
Steps to reproduce the behaviour:

Vanuatu vaccine datafile: https://drive.google.com/file/d/1N5fTxi1rS8Js3g801OSiIDCSxHJZ9vTJ/view?usp=sharing

1. Use the above Vanuatu datafile with mobile V8.0.8
2. Connect to a Mobile store
3. Login as an admin user
4. You should not see settings 

**Expected behavior**

**Smartphone (please complete the following information):**
 - OS: Android 10
 - Version V8.0.8
 - mSupply Desktop V.5.2

**Additional context**

**Comment by katherine-sussol** [comment] 2021-06-09 00:20
Managed to repro, 'isAdmin: false' is being returned from `authenticateAsync` call (used MobileTest which looks like it's supposed to be an admin?)

Checked in mSupply and something seems weird with the permissions...:
![image](https://user-images.githubusercontent.com/65875762/121273024-6920f680-c91b-11eb-9ad5-836336f3c0d5.png)

**Comment by joshxg** [comment] 2021-06-09 00:57
@katherine-sussol 

Soz, I don't know what I'm looking at in the picture 😁  - what record is that?

The mSupply preferences are really crazy.

**Comment by katherine-sussol** [comment] 2021-06-09 01:04
😆  My bad, I got too aggressive with the ✂️ . It's the `[user_store]` table, user_ID is the userID for 'mobiletest' and store_ID I thiiink was the Mobile Team (test) store that I was logged into.

I ended up looking at that table from here because that's the only place I could find the isAdmin thing being referenced in mSupply 😹 :
https://github.com/sussol/msupply/blob/d5dc97f62256f77159d8bb90b35e057e66b0d03f/Project/Sources/Methods/REST_get_records.4dm#L2257

**Comment by joshxg** [comment] 2021-06-09 01:10
Oh right- yeah.. the `permissions` being a `blob` where each `bit` is a particular permission makes it super easy to debug things 😁 

Mobile tries to hit the server to login, and if its succesful, the server replies with a header `isAdmin` and mobile saves the username+password+isAdmin pref to the local db. If mobile can't hit the server, it'll use the local db to auth against.

So I suppose we can assume the permissions blob does not have `isAdmin` set for the user.. (Can breakpoint and check if  https://github.com/sussol/msupply/blob/d5dc97f62256f77159d8bb90b35e057e66b0d03f/Project/Sources/Methods/REST_get_records.4dm#L2258 is getting set, I suppose) which can either be a config mistake (maybe we need to ask someone who actually knows how to use mSupply..) or an mSupply issue?

**Comment by raviSussol** [comment] 2021-06-09 15:57
@katherine-sussol @joshxg I was trying to work out for #4082 yesterday and I got an eye on this issue (since I was working on the mobile yesterday) so thought to have a quick look on this and I think @joshxg is quite right about the fact that this is to do with mSupply desktop rather than the mobile. There is a bug in the desktop side that the `isAdmin` has only been made to handle for the individual user's permission (not for a group's permission). So in the case of Tonga vax server, users are assigned to groups (i.e `Administrator`) and when the mobile makes a call while login to the tablet mSupply web server always checks for the individual user and tries to return its user permission (of which case the permission `79` view/edit preference) always be `false`. So issue needs to be addressed in the msupply repo. Feel free to create an issue in the msupply desktop and you can assign that to me (if you don't want to touch 4D code :-) ) With that being said you can close this issue if you don't find any differences than what I found above.

**Comment by joshxg** [comment] 2021-06-09 18:37
Thanks @raviSussol !

I think it's less about not wanting to touch 4D code and more about not wanting to break more 4D code :trollface:

**Comment by npendergrast** [comment] 2021-06-10 22:08
Hi @raviSussol, I've just tested on the Vanuatu Vax server, however when I have created a new user and given them all the permissions without assigning them to a permission group I still cannot see the Settings on mobile (have synced and logged out and back in).

**Comment by raviSussol** [comment] 2021-06-16 09:18
Hi @npendergrast can you share a video of what step did you do to catch the settings option not showing issue? Ofcourse, share in the TG. Or You can retest this by taking the vanuatu vax datafile with [this](https://github.com/sussol/msupply/pull/8940) mSupply. See if you could still reproduce the above issue.

**Comment by npendergrast** [comment] 2021-06-17 04:41
@raviSussol thanks for your time Ravi. It is in fact working if you tick it manually (you just have to give the permission for the correct store)

**Closed** 2021-06-17 04:47 UTC
Labels: Bug: production, Docs: not needed, Priority: high, production
