### ISSUE TITLE
The navigation screen is still displayed in english when setting up the language to french

### ISSUE THREAD

**Issue by alainsussol** [openmsupply/mobile#2765] opened 2020-04-23 20:37 UTC
## Describe the bug

The navigation screen is still displayed in english when setting up the language to french. The rest of the app seems to be using french but not the Navigation screen. However it is working (ie display french) if I hit the back button to go back to the tablet screen and then click on the mSupply icon. So maybe there is a refresh problem when navigating mSupply which would mean that this and #2764 are symptoms of another problem.

### To reproduce

1. Go to login page
2. Set the language to french
3. log on

### Expected behaviour

Navigation screen should be in french when the language is set to french. Same thing for other language

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: v5.0.0RC1
- Tablet model: Galaxy tab A (SM-T510)
- OS version: Android

**Comment by joshxg** [comment] 2020-04-23 20:50
Similar to #2764 - a side effect of the navigation change.

Rather than languages updating because of app-wide re-render of the app when you close/open the login modal, we will need to explicitly trigger a re-render of the `MenuPage` when the language changes. The other pages are working fine, as they have not already mounted when the language changes, where as the menu page has (guessing)

**Comment by wlthomson** [comment] 2020-05-09 08:18
Confirmed fixed in `v5.0.0-rc3`.

**Closed by wlthomson** 2020-05-09 08:18 UTC
Labels: 5.0.0-rc1, Bug: development
