### ISSUE TITLE
OS adding trailing space to username causing problems

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#233] opened 2016-07-26 01:56 UTC
## Describe the bug

Basically if the user lets auto complete do its thing, it will often put a space at the end of their user name.  The user can't see the space, so they don't realise it has happened.  When they try to log in, mSupply says that their credentials are wrong, but the user can't see anything wrong unless they know what they are looking for.

### To reproduce

1. Initialisation page
2. Enter username, take an auto complete suggestion
3. Enter password
4. Initialise
5. Good chance it gives an error message regarding wrong credentials.

Also, the user login modal. Same thing.

### Expected behaviour

Don't inconspicuously lull user into putting spaces in they don't want and aren't valid.

### Proposed Solution

Adjust the keyboard settings programatically to not leave trailing spaces to begin with:
- There is a [`TextInput` prop autoCompleteType](https://reactnative.dev/docs/textinput#autocompletetype) (that I don't think existed years ago when this issue was first created. The technology is finally here!)
  - Password fields should be 'password'. Username fields 'username'
  - URLs 'none'?
  - Note, this only works for Android, but we don't really support iOS at all so that's fine. 
- Also turn maybe `autoCapitalize` to 'none' if we haven't already.
- Totally feature creep, but could set server URL `defaultValue` to be "https://". Might be annoying for testers/non SSL usage though.

ALT: Removing trailing spaces:
- Just on site name and user name fields.
- Passwords should be exempt cause they shouldn't have auto complete. Spaces should be valid characters.

ALT: Remove ALL spaces:
- Not good, restrictive policy that does not take into account existing sites/users that may have intentionally added them.
- Doubly not good for passwords, as you can't unhash passwords to correct them retrospectively.

### Version and device info

- App version: all
- Tablet model: most
- OS version: most

### Additional context

Super annoying cause of many support tickets. Would be neat if we had a REST api for resetting passwords (via a link sent to associated email sort of thing)

**Comment by joshxg** [comment] 2019-07-01 03:36
I haven't seen this be a problem anymore so assuming it's fixed. @Chris-Petty please reopen if it's not

**Comment by Chris-Petty** [comment] 2019-07-05 00:54
No it's still a problem.

**Comment by Gwalior-84** [comment] 2021-02-11 22:32
This is the cause of the majority of support requests from one country.  Can we just get mSupply Mobile to strip trailing spaces from

- Initial URL
- Store name
- Store password
- User name
- User password

**Comment by Chris-Petty** [comment] 2021-02-11 22:43
I think this curse needs to be lifted so I pumped up the priority label.

**Comment by Chris-Petty** [comment] 2021-02-11 22:47
@joshxg is it easy enough to patch mobile `v5.X.Y`? Not a request to do this issue right now, just scoping out not forcing a major version upgrade for a small but impactful improvement

**Comment by joshxg** [comment] 2021-02-11 22:55
@Chris-Petty Do you know that 6.0 is the most recent version? I wouldn't say patching an older version is easy enough

**Comment by Chris-Petty** [comment] 2021-02-11 23:28
> @Chris-Petty Do you know that 6.0 is the most recent version? I wouldn't say patching an older version is easy enough

Yup, hence the question really. Client currently on mobile v5.1.X, server v4.14.X. I think that's fine for a v6 upgrade? Unfortunately the [compatibility table ](https://docs.msupply.foundation/en:mobile:compatibility)is lacking both most recent versions of the applications :(

**Comment by joshxg** [comment] 2021-02-11 23:32
Oh cool - I didn't know there was a compatibility table.

6.0 requires 4.13: https://github.com/openmsupply/mobile/releases/tag/v6.0.0 

I dunno if there are any clients actually using 6.0.

**Comment by Chris-Petty** [comment] 2021-02-14 20:14
> Oh cool - I didn't know there was a compatibility table.
> 
> 6.0 requires 4.13: https://github.com/openmsupply/mobile/releases/tag/v6.0.0
> 
> I dunno if there are any clients actually using 6.0.

@Gwalior-84 Has one in mind once it has this issue patched into it 😃

**Comment by Gwalior-84** [comment] 2021-02-24 02:14
This issue has raised its ugly head again https://support.msupply.org.nz/cerb6/profiles/ticket/CP-4644-TZ

Can we bump this up the priority list and assign it to a release please @joshxg ?

**Comment by joshxg** [comment] 2021-02-24 03:12
@Chris-Petty were you doing this or no?

**Comment by Chris-Petty** [comment] 2021-02-24 03:22
Hadn't assigned myself, but can

**Closed** 2021-03-08 01:49 UTC
Labels: Bug: production, Effort: small, Priority: high

**Comment by ArpitaSussol** [comment] 2021-03-12 05:43
Tested in v7.0.0 RC11

## Testing

**Initialisation/FirstUsePage**
- [ ] When submitting (pressing next or done on virtual keyboard) URL any leading and trailing white space is removed. 
- [ ] When submitting site name any leading and trailing white space is removed. - 



- [x] When submitting password any leading and trailing white space is **kept**.
- [x] When changing focus (press/click elsewhere in UI, e.g. another field) from URL any leading and trailing white space is removed.
- [x] When changing focus from site name any leading and trailing white space is removed.
- [x] When changing focus from password any leading and trailing white space is **kept**.

**Login Page**
- [x] When submitting user name any leading and trailing white space is removed.
- [x] When submitting password any leading and trailing white space is **kept**.
- [x] When changing focus from user name any leading and trailing white space is removed.
- [x] When changing focus from password any leading and trailing white space is **kept**.

@joshxg @Chris-Petty @mark-prins @wlthomson 
Adding Url, sitename and password randomly such as entering URL at last with spaces and directly hitting "Connect" button results in non sync issue. 
I am not sure this scenario would happen in real or not. Could there be any way to remove trails spaces at the time of triggering of Connect event as well ? 

See the below recorded video. 

https://user-images.githubusercontent.com/58979436/110897357-6830f680-8325-11eb-85d7-075e989ff909.mp4

**Comment by Gwalior-84** [comment] 2021-03-12 07:27
Thanks @ArpitaSussol Isn't this what the code is supposed to do?  Strip leading and trailing spaces from the URL?

**Comment by joshxg** [comment] 2021-03-14 21:49
@ArpitaSussol nice -  new issue here: https://github.com/openmsupply/mobile/issues/3762

**Comment by ArpitaSussol** [comment] 2021-03-15 04:25
Tested in v6.0.3

## Testing

**Initialisation/FirstUsePage**
- [x] When submitting (pressing next or done on virtual keyboard) URL any leading and trailing white space is removed. 
- [x] When submitting site name any leading and trailing white space is removed. - 



- [x] When submitting password any leading and trailing white space is **kept**.
- [x] When changing focus (press/click elsewhere in UI, e.g. another field) from URL any leading and trailing white space is removed.
- [x] When changing focus from site name any leading and trailing white space is removed.
- [x] When changing focus from password any leading and trailing white space is **kept**.

**Login Page**
- [x] When submitting user name any leading and trailing white space is removed.
- [x] When submitting password any leading and trailing white space is **kept**.
- [x] When changing focus from user name any leading and trailing white space is removed.
- [x] When changing focus from password any leading and trailing white space is **kept**.
