### ISSUE TITLE
Name Visibility: Names are not syncing to mobile after making it visible in desktop

### ISSUE THREAD

**Issue by anildahalsussol** [openmsupply/mobile#2416] opened 2020-02-28 06:52 UTC
## Describe the bug

After changing a name visibility in desktop its still not visible in tablet. though mSupply desktop is creating a sync out record for that table.
### To reproduce

1. Go to mSupply desktop and login to mobile store
2. Find name by excluding hidden.
3. Choose any one name and make it visible in that store
4. Check sync out record in desktop and do manual sync in tablet.
5. It wont be visible in tablet.

### Expected behaviour

Names should be visible if its made visible in desktop
### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: 4 rc14
- Tablet model:samsung
- OS version:
- Desktop mSupply version: 409

**Comment by joshxg** [comment] 2020-03-01 00:50
Visible Suppliers:

![image](https://user-images.githubusercontent.com/35858975/75617113-764f2180-5bbf-11ea-82cf-db2eb515ee9c.png)

With invisible suppliers:

![image](https://user-images.githubusercontent.com/35858975/75617117-8ff06900-5bbf-11ea-90c9-ed027ab7cecc.png)

Enable visibility in my store (Zam)

![image](https://user-images.githubusercontent.com/35858975/75617122-aac2dd80-5bbf-11ea-887c-9b318db048c3.png)

Sync out queue:
![image](https://user-images.githubusercontent.com/35858975/75617149-1dcc5400-5bc0-11ea-9816-10fc63bb1e44.png)


Table 93:
![image](https://user-images.githubusercontent.com/35858975/75617146-0beab100-5bc0-11ea-8cd9-7c4428482bd1.png)

Mobile:

![image](https://user-images.githubusercontent.com/35858975/75617164-4d7b5c00-5bc0-11ea-96f0-45b20979cdcd.png)

#### So, you only get the name store join. The `Name` has not been added to the sync out.


--------

Making the store a transfer store on my mobile site:

![image](https://user-images.githubusercontent.com/35858975/75617248-41dc6500-5bc1-11ea-84a4-33c0455c5161.png)


Checking sync out afterward:
![image](https://user-images.githubusercontent.com/35858975/75617258-8962f100-5bc1-11ea-91f0-ef6bdc11e970.png)

It's only the `[name]` of the mobile store.
![image](https://user-images.githubusercontent.com/35858975/75617265-b57e7200-5bc1-11ea-9304-57a36ce07559.png)

---------

However after I reinitialize I have the supplier: 
![image](https://user-images.githubusercontent.com/35858975/75617402-88cb5a00-5bc3-11ea-8040-effe880c567d.png)

So, unless you are talking about something else - I believe this is a desktop problem

**Comment by anildahalsussol** [comment] 2020-03-02 11:38
@joshxg : But table 93 is [name store join]..So it seems the sync out record is created for mobile store.

**Comment by adrianwb** [comment] 2020-03-02 16:21
I'm not entirely clear what the problem is here, but there does seem to be some misunderstanding?

- non-patient names are system data so they should already have been synced to all sites on initialisation, and any changes made to them on the primary since then should sync to all sites
- name_store_join records should sync to the site where the corresponding store is active, on initialisation and on any subsequent change

=> if you only change the visibility in a store, it will only generate `[sync_out]` records for `table_num=93`
=> if you want to re-sync the `[name]` record (`table_num=6`), then you need to save the name as well; but this should not be necessary as the `[name]` record _should_ already be on all sites - if it isn't then that is where the problem lies...

**Comment by adrianwb** [comment] 2020-03-02 19:41
To give an example:

- if you edit store A's sync settings to make store B's site "transfer", that will:
  - sync store A and its name to _both_ store B's site _and_ store A's site
  - make store A visible in store B, and sync the visibility record to store B's site
  - make store B visible in store A, and sync the visibility record to store A's site

- it _won't_ sync:
   - store B and its name to _either_ store A's site _or_ store B's site (you're editing store A)
   - store A's visibility in store B to store A's site 
   - store B's visibility in store A to store B's site
=> if you want to do that, then you need to do the corresponding change on store B as well (i.e. make store A's site a "transfer" in store B's sync settings); after all, transfers can go both ways...

Note that changing the visibility of any name (including store names) in any store will _only_ sync the change to that store's site.

**Comment by joshxg** [comment] 2020-03-02 22:26
Thanks for the clarification @adrianwb 

If we don't mind going through a few more steps!

1. No sync outs for my mobile site - zam

![image](https://user-images.githubusercontent.com/35858975/75720551-9e638f80-5d3b-11ea-9ceb-583a7397a0d4.png)


2. I am turning a store to a transfer store on my mobile site.


![image](https://user-images.githubusercontent.com/35858975/75720658-c7842000-5d3b-11ea-9bd7-10614b550918.png)
![image](https://user-images.githubusercontent.com/35858975/75720747-ec789300-5d3b-11ea-9ba6-bd85e9982267.png)
![image](https://user-images.githubusercontent.com/35858975/75720807-0c0fbb80-5d3c-11ea-9c39-032c704df3eb.png)
![image](https://user-images.githubusercontent.com/35858975/75721150-b7b90b80-5d3c-11ea-8baf-3b0a2f98100f.png)

[namesyncingtest-syncouts.json.zip](https://github.com/openmsupply/mobile/files/4278181/namesyncingtest-syncouts.json.zip)


*Get all the 8 records no worries, and as you say - have edited the mobile store record technically, so do not get the name record for the newly visible store*.

3. Now making my mobile store a transfer store on the store I had just made a transfer on my mobile store (so that I can get the name record for that store..?) *also cleared the sync queue*

#### Was using postman here to remove mobile from being a variable:

![image](https://user-images.githubusercontent.com/35858975/75721853-f13e4680-5d3d-11ea-91c7-d28ab98647a9.png)
![image](https://user-images.githubusercontent.com/35858975/75722748-b1785e80-5d3f-11ea-841c-8facfcfc31bb.png)
![image](https://user-images.githubusercontent.com/35858975/75722860-eab0ce80-5d3f-11ea-9532-84513a692c69.png)

I ONLY received the 3 list master records - forgot to take screenshot but json: [namesynctest-after-force-sync-outs-for-second-store.json.zip](https://github.com/openmsupply/mobile/files/4278188/namesynctest-after-force-sync-outs-for-second-store.json.zip)

4. Opening the second store I am trying to get visible in mobile `SAHABO` - to try and force a sync out:

![image](https://user-images.githubusercontent.com/35858975/75723227-b7227400-5d40-11ea-966c-8331599ab996.png)
![image](https://user-images.githubusercontent.com/35858975/75723344-fbae0f80-5d40-11ea-8200-356f7b55cd1c.png)
![image](https://user-images.githubusercontent.com/35858975/75723387-13859380-5d41-11ea-80dc-91b8ed4cf008.png)
![image](https://user-images.githubusercontent.com/35858975/75723410-2304dc80-5d41-11ea-8f7a-73aa520897ba.png)






----

Thats a lot - but that is where my confusion is. Although I think that making a site a transfer site should sync the store/name records on that site to the mobile site as they are now visible, there doesn't seem to be *any* way to get those records without re-initializing?

**Comment by adrianwb** [comment] 2020-03-03 14:46
> _Get all the 8 records no worries, and as you say - have edited the mobile store record technically, so do not get the name record for the newly visible store_.

All OK up to here anyway...

>     1. Now making my mobile store a transfer store on the store I had just made a transfer on my mobile store (so that I can get the name record for that store..?) _also cleared the sync queue_
> 
> #### Was using postman here to remove mobile from being a variable:
> 
> ![image](https://user-images.githubusercontent.com/35858975/75722748-b1785e80-5d3f-11ea-841c-8facfcfc31bb.png)
> 
> I ONLY received the 3 list master records - forgot to take screenshot but json: [namesynctest-after-force-sync-outs-for-second-store.json.zip](https://github.com/openmsupply/mobile/files/4278188/namesynctest-after-force-sync-outs-for-second-store.json.zip)

I was expecting another `name_store_join` sync record here to make SAHABO visible in Zam (unless it was already visible, which seems unlikely)

>     1. Opening the second store I am trying to get visible in mobile `SAHABO` - to try and force a sync out:
> 
> ![image](https://user-images.githubusercontent.com/35858975/75723227-b7227400-5d40-11ea-966c-8331599ab996.png)

The one screenshot which is missing is of course the one I want to see - the Store tab for the SAHABO store! Is your Zam store visible here? If not, does making it visible generate that elusive missing `name_store_join` sync record when the store is saved?

**Comment by joshxg** [comment] 2020-03-03 17:48
@adrianwb 

yup it was visible

**Comment by adrianwb** [comment] 2020-03-06 15:50
I think the problem is that the "reverse" visibility record of the current store in the other store isn't getting automatically updated/synced when the other store's visibility in the current store changes - see above linked issue

**Comment by joshxg** [comment] 2020-03-08 20:07
awesome thanks for checking this out @adrianwb  -  I'll close this one!

**Closed by joshxg** 2020-03-08 20:07 UTC
Labels: Bug: development, Docs: not needed, Effort: medium, Investigation, Priority: unconfirmed issue
