### ISSUE TITLE
Search filter text is inconsistent between supplier and customer invoice table windows

### ISSUE THREAD

**Issue by DhanyaHerath** [openmsupply/mobile#2796] opened 2020-04-29 03:43 UTC
## Describe the bug

The customer invoice window says Search by customer
![image](https://user-images.githubusercontent.com/29744386/80558815-b8fe7000-8a2f-11ea-9386-9c09f9ef85da.png)

The supplier invoice window says Search by Invoice number
![image](https://user-images.githubusercontent.com/29744386/80558832-c6b3f580-8a2f-11ea-8089-233596ba9fed.png)

### To reproduce

1. Go to the customer invoices window 
2. Observe
3. Go to the supplier invoices window 
4. Observe

### Expected behaviour

They should be consistent I think! I think searching by both is useful but that's another issue...

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

App version: 5.0.0RC2
Tablet model: Galaxy tab A
OS version: Android 8 

### Additional context

Customer and supplier requisitions both have 'Search by invoice number' filter texts

**Comment by wlthomson** [comment] 2020-04-29 07:58
Looks like this might be a duplicate of https://github.com/openmsupply/mobile/issues/1235. It looks like it was worked on but nothing was PRd or merged. Going to keep this as the reference issue and go ahead and delete that one, just to tidy things up a bit.

I think `itemName`, `itemCode` for item pages and `serialNumber` and `otherParty` for others (I can see the usefulness of filtering by comment, but I think more reason for the bigger issue of updating the search interface).

**Comment by wlthomson** [comment] 2020-05-04 23:34
FIxed by #2796.

**Closed by wlthomson** 2020-05-04 23:34 UTC
Labels: Docs: needed, Effort: small, Priority: normal, UX
