### ISSUE TITLE
Customer Requisition quantity is resetting to 0

### ISSUE THREAD

**Issue by anildahalsussol** [openmsupply/mobile#1990] opened 2020-01-23 05:20 UTC
## Describe the bug
While entering quantity in customer requisition resets to 0.

### To reproduce

Please make sure to take MAM datafile recent backup.
1. Goto customer requisition
2. Select any response requisition.
3. Try to enter quantity

### Expected behaviour

It should allow to enter the quantity if SOH is available
### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version:3.1.1
- Tablet model:lenovo, huwaei, telcaast

### Additional context

https://recordit.co/Q3CvbvQPcZ

**Comment by sworup** [comment] 2020-01-23 08:27
@anildahalsussol The issue is in this code block
https://github.com/openmsupply/mobile/blob/dd693c0f23e387043d037f75edc1df39b384827c/src/database/DataTypes/RequisitionItem.js#L161-L178

Here `linkedTransactionItem` is returned as null and the method returns out without setting `suppliedQuantity` in line 176. This `suppliedQuanity` is being used by the input box. 
Since it is not set, the 0 value gets reset on component reset.

We have to check the codes using this method while solving this issue for Customer requisition as this method is being used at multiple places.

**Comment by joshxg** [comment] 2020-01-24 00:41
Closed by #1993

**Closed by joshxg** 2020-01-24 00:41 UTC
Labels: Docs: not needed, Effort: small, Priority: immediate

**Comment by diegoevangelisti** [comment] 2020-01-24 03:43
## Testing

*Datafile must have a `RequisitionItem` with no `TransactionItem`, where the `RequisitionItem` is for an unfinalised `RequisitionItem`, and the underlying `Item` has stock on hand greater than 0 -- This was originally found on the Medical Action Myanmar datafile - using the latest backup and the HTY A store*

- [x] Issuing stock for the line is possible and doesn't reset to 0.
- [x] Issuing stock in the unfinalised customer requisition correctly reduces stock in the store, even when unfinalised.
- [x] Finalising the response requisition will enable the linked customer invoice to be visible in `CustomerInvoicesPage`

**Success**
