### ISSUE TITLE
Bottom of auth page chopped off in Nexus 7 tablet

### ISSUE THREAD

**Issue by GaryWilletts** [openmsupply/mobile#114] opened 2016-07-15 14:10 UTC
Build 4

Expected: opening app first time, complete page is visible

Actual: on Nexus 7 tablet Login button is chopped off the bottom. Can't scroll the window or change the orientation so no way to proceed. Screenshot attached. Adrian tells me that this is the same in the emulator when emulating a Nexus 7.

![mobile login problem](https://cloud.githubusercontent.com/assets/11517184/16876905/c140b7b2-4a9d-11e6-8061-195b120a67c4.png)

**Comment by joshxg** [comment] 2019-07-01 03:31
Duplicate of #414 - closing

**Closed by joshxg** 2019-07-01 03:31 UTC
Labels: Priority: Normal
