### ISSUE TITLE
Crash on deleting new records

### ISSUE THREAD

**Issue by alainsussol** [openmsupply/mobile#2780] opened 2020-04-24 19:38 UTC
## Describe the bug

mSupply crash (close) when I delete new un-finalised customer invoice with lines or no lines. It is working fine when deleting existing customer invoices. Seems also to work fine when creating new customer invoice, get out of mSupply and reopen it again and then delete the invoice

### To reproduce

1. Go to Customer invoice
2. Click on New customer invoice and add lines or not. 
3. From the customer invoices list, delete the customer invoice

### Expected behaviour

mSupply should not crash

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: v5.0.0RC1
- Tablet model: Galaxy tab A (SM-T510)
- OS version: Android

### Additional context

You might have catch that with bugsnag :)

**Comment by wlthomson** [comment] 2020-04-25 08:16
Did a bit of digging, looks like the finalise modal is trying to access the record after it is deleted from memory. I think what's happening here:

1. Navigate to the CI (or SI, stocktake).
2. Finalise modal state is updated to "point" to that record.
3. Navigate back to customer invoices page, finalise modal state isn't changed.
4. Delete the CI.
5. Modal is rerendered, attempts to access the now deleted record.
6. See error.

**Comment by wlthomson** [comment] 2020-04-27 02:31
Fixed by #2781.

**Closed by wlthomson** 2020-04-27 02:31 UTC
Labels: Bug: development, Docs: not needed, Effort: small, Module: dispensary, Priority: release blocker

**Comment by diegoevangelisti** [comment] 2020-04-29 03:03
## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [x] Create a new customer invoice and navigate back to customer invoices page. No error is thrown on deleting the new invoice. --PASS--
