### ISSUE TITLE
(Kiribati) Merged patient vaccinations not displaying in Patient Vaccination History

### ISSUE THREAD

**Issue by adamdewey** [openmsupply/mobile#4484] opened 2021-11-01 21:47 UTC
## Describe the bug

Kiribati have patients that have been entered into the system twice through human-error. 

Each of the patient records has had a vaccination event recorded against them. 

Kiribati now want to merge the patients records in mSupply Desktop to eliminate one of the patient records but retain both vaccination events. 

It appears that the vaccination event is correctly transferred from the eliminated patient record to the preserved patient record in mSupply Desktop, but the Patient Vaccination History in Mobile does not display the transferred vaccination event. 

![image](https://user-images.githubusercontent.com/19318937/139745726-a092c210-bc34-4241-88dd-b3d2fb7ccf0c.png)

![image](https://user-images.githubusercontent.com/19318937/139745757-08fd3198-0364-4de3-9c5f-73afa62d34bd.png)

![image](https://user-images.githubusercontent.com/19318937/139745769-dfb25518-09d2-431d-b64f-68e23c58caa6.png)

(Seems that there's some timing discrepancy between the server and tablets here as date is off by 1 day) 

![image](https://user-images.githubusercontent.com/19318937/139745812-078d2d22-8256-499e-a3e1-f26fbca44cd1.png)

![image](https://user-images.githubusercontent.com/19318937/139745987-a2ba6206-7b07-403d-99d6-0cb2d69cf683.png)

### To reproduce

Steps to reproduce the behaviour:

1. Create a new patient record in Mobile
2. Administer a vaccination
3. Create another new patient record in Mobile
4. Administer another vaccination
5. Merge the patient records in Deskop
6. Observe that Desktop shows both vaccination events but Mobile only displays one. 

### Expected behaviour

Both the original vaccination event and the transferred vaccination event to be displayed in the Patient Vaccination History page. 
### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: 8.3.0-rc1
- Desktop version: 5.03
- Tablet model: Lenovo TB-X505N
- OS version: Android 10

**Comment by joshxg** [comment] 2021-11-01 23:33
Thanks @adamdewey 😁 

I'm not 100% sure on all of the issues, but I would start with merging properly:

Merging is done here: https://github.com/openmsupply/mobile/blob/a43354062a621a9d51a741bf52eba226c8e2a725/src/sync/incomingSyncUtils.js#L1290

It has not been changed since we started  having patients in mobile 

Should be quite easy to implement - the merge logic itself isn't very complicated, though the `mergeRecords` code is, in my opinion, confusing to work with

**Comment by katherine-sussol** [comment] 2021-11-03 02:19
> Merging is done here:
> 
> https://github.com/openmsupply/mobile/blob/a43354062a621a9d51a741bf52eba226c8e2a725/src/sync/incomingSyncUtils.js#L1290
> 
> It has not been changed since we started having patients in mobile
> 
> Should be quite easy to implement - the merge logic itself isn't very complicated, though the `mergeRecords` code is, in my opinion, confusing to work with

Thanks @joshxg yeah I _think_ the merge process is missing an update of name notes (and maybe some other stuff too). If I clear the app data and resync it pulls the merged records and history fine from Desktop... will have a look 👀

**Comment by joshxg** [comment] 2021-11-03 02:26
@katherine-sussol  thanks

I believe this might take a *little* bit of desktop looking into also. Merging isss a littttle bit complicated..

Some info which might cause confusion or help:

- When a merge happens on the server, there is a `sync_out` record with a sync type `M` (different to `U` for updates and `D` for deletes etc)
- Names usually are only merged on the central server, as they're central data, they can only be updated/deleted there. I believe this might be why we only touch the master lists after a merge? Though, they shouldn't be touched either.. so turns out i'm not very sure of the merge logic..
- Patients however, have a home store and technically shouldn't be updated anywhere but there. I believe they're able to be merged in kiribati because the god mode patient dangerous mode deity thing is on.

**Comment by adamdewey** [comment] 2021-11-03 02:43
Oh interesting.. I helpfully didn't include which store I was in in the screenshots above when I did the merge...

Hmm,  I would have thought I would have gone into the same store I created the patient in, but you never know with this guy

**Comment by adamdewey** [comment] 2021-11-03 02:45
But also, thinking about it we do need to be able to merge cross-stores in case different teams (stores) added patient records multiple times (because they couldn't find the original record due to slight spelling variation etc)

**Comment by joshxg** [comment] 2021-11-03 02:48
I suspect so. Duplicates have always been a pretty big concern, we're just not handling them very well .. :) 

Technically, I believe you can transfer the 'home store' of a patient, which means you can still do the merge

**Comment by adamdewey** [comment] 2021-11-03 02:50
Ah ok, as long as there's some kind of way to do it then that's all good :)

**Comment by katherine-sussol** [comment] 2021-11-04 02:48
(I think) a small tweak addresses the issues with vaccinations not being migrated - if we add the NameNote and ADR name fields here:
https://github.com/openmsupply/mobile/blob/a43354062a621a9d51a741bf52eba226c8e2a725/src/sync/incomingSyncUtils.js#L1248-L1259

Unfortunately there's still a bit of weird behaviour going on. I think it's pre-existing as it exists in the current release but if you're trying to do something with a patient (e.g. dispense something to them) and they get deleted due a merge (or I guess even if it's deleted on the central server? I haven't tested that yet), the app will crash because the record being edited has suddenly disappeared 🤣 . Trying to see what to do about this but it's also sort of edge case-ey.

**Comment by Chris-Petty** [comment] 2021-11-08 22:56
@joshxg @katherine-sussol I'm wondering how exactly the vaccination records are structured and how they play into merging (just so I can wrap my head around the desktop side).

1. There is a single name note that contains JSON data of all the vaccines for a patient?
2. After merge does it merge the name_notes (or should it), or does the patient just end up with their vaccination data across 2 name_notes?

Just judging from Adams photos and my guesses, I guess there are indeed two name_notes on the patient and mobile just flattens the data across them when showing in UI?

**Comment by joshxg** [comment] 2021-11-08 23:00
I don't remember - I can look into it soon.

Are you looking at doing some work in this area for desktop? Kat has a PR that needs reviewing - seems it would be very useful if you could review the PR?

**Comment by Chris-Petty** [comment] 2021-11-08 23:17
> I don't remember - I can look into it soon.
> 
> Are you looking at doing some work in this area for desktop? Kat has a PR that needs reviewing - seems it would be very useful if you could review the PR?

@adamdewey nudged me on server side scripts to manage merging a whole bunch of patients as specified from a spreadsheet, but figured that the fixing of merging would be a prerequisite 😁 ! So just checking in here to see what's up. I'm going to avoid reviewing mobile side of this- I've had no involvement for a long long time (no idea about the merging implementation). Generally high priority focus on site refactoring on server but can manage making sure the desktop side of this well defined and got people on it!

**Comment by katherine-sussol** [comment] 2021-11-08 23:23
@Chris-Petty The name notes are currently separate, so every time there is a new vaccine -> new name note gets created. The vaccine history on mobile pulls all name notes with patient event with code of 'vaccination'.

The PR is pretty small (given the merging framework already existed in mobile and seems to work _mostly_ as expected):
Before deleting the merged patient all name_note records pointing to the to-be-deleted patient get updated to the to-be-kept patient record (and it does the same for some other linked records that were missed previously).

**Comment by Chris-Petty** [comment] 2021-11-09 00:44
> @Chris-Petty The name notes are currently separate, so every time there is a new vaccine -> new name note gets created. The vaccine history on mobile pulls all name notes with patient event with code of 'vaccination' (and linked to selected patient)
> 

Interesting- In my memory there was a time that it was just one name_note? I recall like an accidental recursive thing that every time a new vaccine happened it took the old json and nested it in the new json (which would grow exponentially I think?)? Was that changed to individual notes for each event? Is my memory completely off? My only involvement was a blip of helping Anil write import scripts months ago after all.

What I'm hearing is that it seeeeems merging on the desktop side is OK? I think I understand enough here to double check. At a glance it seems added to the right place to work, which seems confirmed by details in Adams issue! So long as the merge doesn't need to take the 2 notes and munge the JSON into one, I think we're good! (Clarity on that is basically the itch I was trying to get to here)

> The PR is pretty small (given the merging framework already existed in mobile and seems to work _mostly_ as expected): Before deleting the merged patient all name_note records linked to the to-be-deleted patient get updated to be linked to the to-be-kept patient record (and it does the same for some other linked records that were missed previously).

I take that it's pretty small, that's good. But given the experience and ownership of code here (as far even as good protips earlier on this issue) I think it makes much more sense for @joshxg to pickup the review- probably half time and of better quality than I can do.

**Comment by katherine-sussol** [comment] 2021-11-09 01:45
> Interesting- In my memory there was a time that it was just one name_note? I recall like an accidental recursive thing that every time a new vaccine happened it took the old json and nested it in the new json (which would grow exponentially I think?)? Was that changed to individual notes for each event? Is my memory completely off? My only involvement was a blip of helping Anil write import scripts months ago after all.

Oh, hm I think you are remembering the `name_note` recursion correctly, it was removed with this commit, which went into 8.3.0: 419443d.

The original implementation always did create separate `name_note` records from the looks of things though (so I guess there was a period where we had multiple `name_note` records and unintentional recursion... 🤔 ): https://github.com/openmsupply/mobile/pull/4303

**Comment by katherine-sussol** [comment] 2021-11-11 06:49
Closed by #4497. Tangentially related issue logged here: https://github.com/openmsupply/mobile/issues/4503

**Closed by katherine-sussol** 2021-11-11 06:49 UTC
Labels: Priority: high, Bug: ????, Status: In progress

**Comment by ArpitaSussol** [comment] 2021-11-12 09:42
Tested in v8.3.1-rc0

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [x] Merge two patients in Desktop (both of their home stores need to be the store you are logged into it seems), for Kiribati they will still show up in all mobile stores due to patients syncing everywhere. The vaccination records for both patient records should appear in mobile against the patient that was retained.
