### ISSUE TITLE
Kiribati Vax: Editing Vaccination events' sub-pages without syncing overrides each other

### ISSUE THREAD

**Issue by nisha-dangol** [openmsupply/mobile#4909] opened 2022-08-31 09:27 UTC
## Describe the bug
Everytime you change the vaccine event details together (Extra info, Additional details and vaccination event form), all the changes do not get saved together, i.e, only the Vaccination event changes are reflected after the change while the other changes are discarded 

### To reproduce
Steps to reproduce the behaviour:
1. Go to a patient's vaccination history
2. Edit additional details like dose number, arms. etc ann Save
3. Now edit Vaccination Event; like vaccinator or vaccine and save.
4. Sync
5. Look back to that same patient vaccine history
6. See error: only last changes in vaccination event form is seen, the previous changes in other forms is discarded

### Expected behaviour
definitely not as above?

### Proposed Solution
Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info
- App version: latest [apk](http://t.ly/0uZv)

**Comment by sworup** [comment] 2022-08-31 09:34
@nisha-dangol This is a known issue. I know this exists but fixing it can take some time. Maybe on next phase.

**Comment by sworup** [comment] 2022-08-31 09:42
There are 2 ways we can fix it:

1. Once a Vax event sub-page has been edited we lock further editing until the data is synced. I do not like this.
2. The Vax event page contains an instance of original vax event details which is updated by each sub-page but this instance never updates, this most probably is the cause of the issue. Whenever we save a sub-page we update the original vax details instance object and changes coming after will be applied on top of it.

**Comment by sworup** [comment] 2022-09-08 03:43
Merged with #4921 4919

**Closed by sworup** 2022-09-08 03:43 UTC
Labels: Priority: high, Bug: development, Project: Kiribati COVID-19 Vax

**Comment by nisha-dangol** [comment] 2022-09-08 06:58
## Testing
Tested in latest apk

### Tests
- [x] Select a vax event that belongs to current store so that it would be editable
- [x] Edit Page 2: Additonal Details data, save it
- [x] Edit Page 3: Vaccination event data and save it.
- [x] Now sync the changes
- [x] Load the vax event again and check, the Page 2 should not have been overridden it should have the latest changes.
- [x] Page 3's save would auto save Page 2's change so you actually do not need to click Page 2's save button, page 3's click should save them both.
- [x] That is not the case for Extra Informaiton, extra information is independent from the next 2 pages
