### ISSUE TITLE
Upgrading from 8.5 to 8.6 is causing some data loss

### ISSUE THREAD

**Issue by nisha-dangol** [openmsupply/mobile#4943] opened 2022-09-23 05:24 UTC
## Describe the bug
While upgrading the existing syncing mobile store from 8.5 to 8.6, the patient lists are all gone from the dispensary.

### To reproduce
Steps to reproduce the behaviour:
1. Get a mobile store sync setup in 8.5.
2. You can create some patients there as well for testing purpose.
3. Now, upgrade it to latest 8.6 from [here](http://t.ly/CpdV)
4. Open it and click Dispensary module
5. See error: the patient list is literally empty; not even the patient created before is there:
![Screen Shot 2022-09-23 at 11 07 13](https://user-images.githubusercontent.com/59193490/191896589-24bdce09-c3cb-4ebf-aeef-ebb8989277f0.png)
6. Search for patient in the lookup. Click on it.
7. Read that alert message toast:
![Screen Shot 2022-09-23 at 11 08 00](https://user-images.githubusercontent.com/59193490/191896658-06062409-02eb-439f-9d30-10f71ac037b0.png)

### Expected behaviour
Data should not disappear like that whatsoever

### Proposed Solution
Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info
- App version: 8.6

**Comment by sworup** [comment] 2022-09-23 05:28
@nisha-dangol the 2nd screenshot message says the patient already exists while you tired to lookup and load from server. 

That means Patient record is there, just not showing for some strange reason.

Is it patient data only or other data are also missing?

**Comment by adamdewey** [comment] 2022-09-23 05:31
Which version of Desktop are you syncing with @nisha-dangol - I know that a later version of Desktop is required as there were some small table changes, I wonder if this would affect it at all?

**Comment by nisha-dangol** [comment] 2022-09-23 05:37
> Is it patient data only or other data are also missing? Like vaccine event info?
>
The vaccination history are there as long as we search online. It's weird that the homestore patient also do no show up at first in Vaccinations:
![Screenshot_2022-09-23-11-17-10-467](https://user-images.githubusercontent.com/59193490/191897792-c279a025-317a-44d7-96c7-a3647fbce15d.jpeg)

Only after clicking `Search online` button, it shows up:
![Screenshot_2022-09-23-11-17-38-084](https://user-images.githubusercontent.com/59193490/191897796-c401c090-38c7-4675-b623-fcdddb3c08da.jpeg)

**Comment by nisha-dangol** [comment] 2022-09-23 05:38
> Which version of Desktop are you syncing with @nisha-dangol - I know that a later version of Desktop is required as there were some small table changes, I wonder if this would affect it at all?
>
The kiribati-vax datafile was minimised in the latest 6-04-01 exe. So, desktop is in 604.

**Comment by adamdewey** [comment] 2022-09-23 05:45
Oh ok, hmm, possibly minimising is interfering with it??

Will be interesting to see what happens when upgrading via MEMDM with @bijaySussol

**Comment by nisha-dangol** [comment] 2022-09-23 05:50
> Oh ok, hmm, possibly minimising is interfering with it??
> 
I don't think so. Tried this previously with kiribati-vax datafile on training test server as well. Saw the same behavior there! So, re-tested with the minimised datafile! 

> Will be interesting to see what happens when upgrading via MEMDM with @bijaySussol
>
Yup, let's hope it works out well!

**Comment by sworup** [comment] 2022-09-27 03:34
For now I think, the issue is related to isdeleted of name and name note being null instead of false in mobile. In desktop it is false by default so no problems there.

**Comment by bijaySussol** [comment] 2022-09-27 04:46
@sworup @adamdewey : 

I had a look on this issue comparing the nature of Mobile data between: 8.4.x, 8.5.x and with 8.6.0 (The one we are aiming for Kiri-VAX).

This is how it in terms of mobile data.
--------

- Directly installing 8.6.0 i.e no upgrade
   - Patients shows fine
   - No `[name]is_deleted` with `[name]isDeceased`
   - This means a re-dump or re-initialization which i personally think, should only be our last option
      - Also @adamdewey shared, It took like a week to finish syncing last time
      - And we probably going to face the same issue again in Future
Mobile realm data under `name` look like this:
![photo_2022-09-27_09-54-26](https://user-images.githubusercontent.com/13144882/192432740-7dec2fbb-56e3-42a5-abf3-ea131e21f1f5.jpg)

--------
- Installing clean 8.4 -> upgrading to 8.5
   - Patients shows fine
--------

- Installing clean 8.5 -> Upgrading to 8.6
   - Patients failed to show
   - There is `[name]is_deleted` with `[name]isDeceased`
      - Is all set to `Null` values
![photo_2022-09-27_09-54-21](https://user-images.githubusercontent.com/13144882/192433035-ab338453-303a-451f-9f17-1404e7e08b29.jpg)

So wondering what is the difference when `Directly installing 8.6.0 i.e no upgrade` and `Installing clean 8.5 -> Upgrading to 8.6` @sworup .

But it is clear that, when upgrade take places field `[name]is_deleted` with `[name]isDeceased` is set to Null which is what i think is causing an issue which i think is your point as well @sworup and having different schema on realm store is causing an issue.

Or We can OR them? But will be a bandage

--------

- Why does it shows on upgrade only but not on directly installing V8.6.0 version?
   - If you can crack that, I think we might have a solution

What i tried:
- I created a FC code to set those field and ran from central server, Mobile using V8.6.0
   - No luck


Field: 
- [name]is_deleted Seems to be mandatory one - as best of my understanding
- [name]isDeceased is a optional where they can either select or not
   - Both of them hold the Boolean value
   - And those fields are already exposed for Kiri-Vax server

**Comment by bijaySussol** [comment] 2022-09-27 14:23
@sworup : 
I think we need a migration code [here](https://github.com/openmsupply/mobile/blob/master/src/dataMigration.js) to set `isDeceased` & `isDeleted`, but I can easily make a mistake.
If it is, setting them will solve the problem.
As case we are dealing is: `isDeceased and isDeleted` is not considered on <=8.5.0, and it does from >=8.6.0
But would be nice to get feedback from @mark-prins.
Thanks

**Comment by sworup** [comment] 2022-09-27 15:43
> @sworup : 
> I think we need a migration code [here](https://github.com/openmsupply/mobile/blob/master/src/dataMigration.js) to set `isDeceased` & `isDeleted`, but I can easily make a mistake.
> If it is, setting them will solve the problem.
> As case we are dealing is: `isDeceased and isDeleted` is not considered on <=8.5.0, and it does from >=8.6.0
> But would be nice to get feedback from @mark-prins.
> Thanks

@bijaySussol i have added migration code there and had it running without any checks. Strangely while running actual version upgrade, migration code is not running for some reason. I am investigating.

**Comment by bijaySussol** [comment] 2022-09-28 04:59
> @bijaySussol i had added migration code there and had it running without any checks, earlier today. Strangely while running actual version upgrade, migration code is not running for some reason. I am investigating.

Great @sworup 
Once you figured this out, We are ready for deployment for VAX after some minimal test
Cheers

**Comment by sworup** [comment] 2022-10-06 06:04
Merged with #4948

**Closed by sworup** 2022-10-06 06:04 UTC
Labels: Priority: high, Bug: production, Project: Kiribati COVID-19 Vax
