### ISSUE TITLE
Prescriber: Adding/Updating Prescriber's Address/Address 2 field is not reflecting/saving 

### ISSUE THREAD

**Issue by ArpitaSussol** [openmsupply/mobile#4133] opened 2021-06-16 09:33 UTC
## Describe the bug

Adding/Updating Prescriber's Address/Address 2 field is not reflecting/saving. It always shows blank

### To reproduce

1. Go to Dispensary -> Add Prescriber
2. Fill the necessary details and enter value for Address & Address 2
3. Open the Prescriber through Edit icon
4. See error. Address & Address 2 field is empty

### Expected behaviour

Address & Address 2 field should reflect the saved value

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: V8.1.0 rc1
- Tablet model: Samsung Tablet
- OS version: 8.1

**Comment by katherine-sussol** [comment] 2021-06-17 02:44
Reproduced on 8.1.0-rc1 - looks like the address fields are being saved (can view in realm explorer and when synced to Desktop the API returns them correctly).
But it looks like the addresses are not being loaded correctly on the edit prescriber screen..
Also when a remote prescriber lookup is done, address1 and address2 isn't being saved correctly

**Comment by katherine-sussol** [comment] 2021-06-18 03:33
Closed by #4144

**Closed by katherine-sussol** 2021-06-18 03:33 UTC
Labels: Bug: development, Docs: not needed, Effort: small, Priority: low

**Comment by ArpitaSussol** [comment] 2021-07-06 11:44
Tested in V8.1.1 rc3

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [x] Create new prescriber and try to edit, validate that the address shows up correctly
- [x] Lookup a remote prescriber and try to edit, validate that their address shows up correctly
