### ISSUE TITLE
Need to handle "00/00/00" date while pulling from server

### ISSUE THREAD

**Issue by anildahalsussol** [openmsupply/mobile#3928] opened 2021-04-13 06:17 UTC
## Describe the bug

Now while initializing the tablet it stops if it finds records with the date "00/00/00".

### To reproduce

1. You can create a requisition from the tablet.
2. Then sync it to the server.
3. Now clear your data from the tablet and resync everything.
4. You will get a message while pulling records.

### Expected behaviour
Ways to bypass it or if we can handle that one properly.

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: 6.0.3
- Tablet model: android 8.1
- OS version:

### Additional context

![photo_2021-04-12 17 25 10](https://user-images.githubusercontent.com/18479204/114505267-d849d980-9c4f-11eb-83cc-2b7414017fc2.jpeg)

**Comment by anildahalsussol** [comment] 2021-04-13 06:17
Will check in version 8 if it still exists or not.

**Comment by joshxg** [comment] 2021-04-13 07:13
@anildahalsussol This one will still exist on `8.0`

**Comment by joshxg** [comment] 2021-04-13 07:13
linked: #3925

**Comment by joshxg** [comment] 2021-04-13 07:13
note: this generally occurs when you are initializating a site with a requisition which is `sg` status (Is that right @anildahalsussol ?)

**Comment by anildahalsussol** [comment] 2021-04-13 07:58
@joshxg : Yes

**Comment by katherine-sussol** [comment] 2021-06-04 03:56
Duplicate of the linked issue #3925 which is now closed

**Closed by katherine-sussol** 2021-06-04 03:56 UTC
Labels: Bug: production, Closed: duplicate, Effort: small, Priority: normal
