### ISSUE TITLE
Cryptic error message when hardware ID already exists for Mobile sync site

### ISSUE THREAD

**Issue by adamdewey** [openmsupply/mobile#4388] opened 2021-08-30 10:03 UTC
## Describe the bug

Similar to https://github.com/openmsupply/mobile/issues/4380 

I got confused by the following error message: 

![image](https://user-images.githubusercontent.com/19318937/131322682-722eb7e6-374d-477b-ab20-91ee21731a78.png)

Turns out it means that there was already a hardware ID associated with that sync site. 

Clearing the hardware ID meant I could proceed with the initialisation. 

### To reproduce

Steps to reproduce the behaviour:

1. Attempt to initialise a tablet that already has a hardware ID associated

![image](https://user-images.githubusercontent.com/19318937/131322856-084e9a2e-ce66-4b9b-bd3c-4d5407f5ef4b.png)

### Expected behaviour

The message tells me why I can't initialise the tablet in more plainer English. 

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: 8.3.0-rc0
- Tablet model:
- OS version:

**Comment by mark-prins** [comment] 2021-08-31 01:42
Unable to reproduce. Currently using v8.2.3 and the WHO demo server

**Comment by mark-prins** [comment] 2021-08-31 01:47
fixed by #4382

**Closed by mark-prins** 2021-08-31 01:47 UTC
Labels: Bug: ????
