### ISSUE TITLE
Allow saving prescriptions in a state before finalising 

### ISSUE THREAD

**Issue by DhanyaHerath** [openmsupply/mobile#4652] opened 2022-04-07 03:27 UTC
## Is your feature request related to a problem? Please describe.
Ivory Coast want to be able to save a prescription without it being finalised (ie. they want to be able to close the prescription, come back to it, and still be able to edit it). 

## Describe the solution you'd like

**Proposed Solution**
- Add some kind of button ('Save for later'? 'Save and Close'? 'Confirm and Close'?) to step 2 and step 3 of Dispensing in Mobile:
  -  ![image](https://user-images.githubusercontent.com/65875762/173487100-ce4de934-9951-4895-a1fc-132e35795468.png)
- When this button is clicked, exit out of dispensing without deleting the prescription in 'cn' state
- On the dispensing menu, move the search bar (and table) down so there is room for an extra toggle ('prescriptions') - this is in line with the CI/SI search bar positioning:
  - ![image](https://user-images.githubusercontent.com/65875762/173490778-86692c36-8289-4bb0-ba84-b6bda17ad61d.png)
- On the new screen display all 'cn' prescriptions (just another table similar to 'current' CIs)? This will allow deletion but not finalisation
  - Clicking any 'cn' prescription will take the user back to step 2 of the dispensing flow (exact page up for discussion, but there isn't too much to be done on step 3 and step 1 is just picking a prescriber, which is arguably not yet a valid prescription).
  - The dispensing parameters will be pre-populated with the previously entered details
- Believe 'Customer Invoices' already excludes confirmed prescriptions from the 'current' tab - but to be double checked (don't want customers to be able to edit here).
- There is no requirement for any changes to how finalised prescriptions are handled/displayed - so retain current behaviour, i.e:
  - Patient history will continue show a patient's finalised dispensing history (believe un-finalised ones will not show up here - to be double checked)
    - ![image](https://user-images.githubusercontent.com/65875762/173491371-d26eb789-6e44-451f-84e2-cc2212ffd949.png)
  - Finalised prescriptions will continue to show up as a 'Past' customer invoice (weird - but this is current behaviour, and it is not editable 🤷)
    - ![image](https://user-images.githubusercontent.com/65875762/173491722-901aa017-a564-4855-b003-b96de3f9545e.png)
    - ![image](https://user-images.githubusercontent.com/65875762/173491423-93bef4aa-ca54-41a1-8a2f-73ab9722a555.png)

**Other considerations/Info**
- Selecting a patient on the dispensing page already creates a transaction in mobile in a confirmed state - current mobile behaviour is to delete it when 'cancel' is pressed on any of the tabs. It's currently possible for these to get lost in the aether (at least from a UI perspective) if someone is mid-dispensing and force closes the app.
- Tested dispensing with payments enabled, and the app will crash if a payment amount is less than the total sell price and attempting to confirm a prescription. To be addressed as a separate issue. 
- The buttons are in an odd place when payments are not enabled. Would really like to move them down for consistency:
  -  With payments ![image](https://user-images.githubusercontent.com/65875762/173493007-c9e098b7-f23a-43bc-a522-db3911eb06ab.png)
  - Without payments ![image](https://user-images.githubusercontent.com/65875762/173492869-558505ec-b138-43a0-9545-d1c368e77f37.png)

## Implementation

**A description of how the solution would best be implemented in the code base**

## Describe alternatives you've considered

- Splitting out actual dispensing from patients into two separate menu options
  - Pros: Can follow the existing 'Current/Past' toggle behaviour used for CIs/SIs/Requisitions 
  - Cons: The menu is already getting pretty cluttered, and adding a sub menu adds an extra step to the process...
- CIs in 'cn' state are editable already - update the UI to let users edit prescriptions there (add in extra fields for prescriptions?)
  - Pros: Don't need to add extra screens to mobile
  - Cons: Confusing. Prescriptions are conceptually different from CIs so going into the CI menu to edit it is not intuitive 

## Additional context

Job Code: 

CILIP-P3M | Côte d'Ivoire (not billable) Phase 3 - Mobile Customizations
-- | --

Requirement: [NEXF025](https://docs.google.com/document/d/1wbz3MFvEpNkOz6taXJp4_kPqnTjbD0Q2/edit#heading=h.8wbvj8dsr05r)

56 hours budgetted

[NFM_CUST] CI NFM3 - Customisations

**Comment by anildahalsussol** [comment] 2022-05-05 04:24
@DhanyaHerath @katherine-sussol : Now we have to confirm the button which actually finalizes the prescription. So I was thinking can we just add another button "Confirm" and "Finalise" so that if the user clicks on confirm then it will just save the data which will be in "Cn" status and can be editable from the customer invoice window?

**Comment by DhanyaHerath** [comment] 2022-05-05 04:30
Good question @anildahalsussol! I don't think we've thought through the design of this yet, and looking through mobile docs, it doesn't look like there are other design examples we can follow. 

@katherine-sussol am I missing anywhere, does mobile have the concept of "confirming"/saving an invoice?

**Comment by katherine-sussol** [comment] 2022-05-05 04:53
@DhanyaHerath not explicitly. For customer invoices, if the user navigates away from the screen (e.g. by pressing the back button on the top of this screen: https://wiki.msupply.foundation/_detail/en:mobile:user_guide:customer_invoice_master_list.png?id=en%3Amobile%3Auser_guide%3Acustomer_inv) it will be saved as a 'confirmed' transaction (which then appears under the 'current' tab). Someone can come in later, open it up and then just tick the green finalise button.

I think the main problem with dispensing is that it's a 'wizard' flow and the UI is completely different to the CI editing page... So we could reuse the confirmed CI UI, but then would need to think about how to edit the prescriber and other dispensing specific info (e.g. usage directions).

**Comment by bijaySussol** [comment] 2022-05-09 04:32
Checking the behaviour of Customer invoices behaviour in current Mobile version, When the customer invoice is entered and not finalized, then that customer invoice status is on status `cn`.

Probably, It would be quicker to apply the same logic as Customer invoice, maybe it is already there?

**Comment by katherine-sussol** [comment] 2022-06-14 04:56
@DhanyaHerath and I had a chat on the IC requirement - the issue description has been updated with a proposed solution and some alternatives that were previously discussed, along with a few things found while testing the dispensary.

@mark-prins any thoughts on how terrible this is for mobile and/or how annoying this will be (for developer or user)? Our thoughts were along the lines that dispensing is already quite deviant from the standard use cases ... so didn't feel we should be overly compelled to try to maintain consistency with those 🤔. 
I couldn't find Pauline on Github so will send a link separately!

**Comment by katherine-sussol** [comment] 2022-06-14 05:34
There is also some discussion of the same request previously raised by @bijaySussol : https://github.com/openmsupply/mobile/issues/4122 - will close the other as a duplicate

**Comment by bijaySussol** [comment] 2022-06-14 06:03
> There is also some discussion of the same request previously raised by @bijaySussol : #4122 - will close the other as a duplicate (sorry - had to pick one!)

Its looks like i understood what is coming from Ivory coast :-p
It had a proper info plus with Job code, this need to be keep opened

Cheers

**Comment by mark-prins** [comment] 2022-06-16 07:07
We deliberately did not allow editing of prescriptions, even though it was wanted by CdI originally. There were too many challenges.. one of which could be rehydrating the state, to get you back to the point in the wizard. More of a concern was how to arrange the UI and what to do about the dispensing section overall

I don't have any concerns about differences in flow from other areas in mobile as the dispensing workflow is different already. We should return to the dispensing workflow when editing non-finalised prescriptions though, as you have it in the description. Possibly not show prescriptions in the customer invoice list at all?

One of the original concerns was how to get back to prescriptions which are unfinalised. I think that we need a screen which lists prescriptions - I think it would be weird going to a list of patients and searching for a prescription. That would only work if the list showed names of patients who had unfinalised prescriptions. and that's a bit odd.

So it would then require reworking the whole dispensing area, with an initial screen showing a prescription list, and an additional step for dispensing - you would need a patient selection list to show.. i.e. 

- Dispensing shows a list of prescriptions
- this has a 'New prescription' button
- Clicking on 'New prescription' gives you a list of patients.. and we start as usual from there
- Clicking on an unfinalised prescription takes you to the item selection step
- Clicking on a finalised prescription.. takes you to step 3 but with everything disabled? Or we don't show fn prescriptions?
- We move patient history and ADR and patient edit somewhere? Maybe a list of patients from the main screen?
- We add a button to delete a prescription? currently 'cancel' breaks you out of the wizard workflow - if you are editing then this action is still valid, but, I would argue, it doesn't tell you that you are going to delete the prescription. A separate action is required for that. If we allow saving, then what does 'cancel' do when you are creating? To me, it cancels the creation, i.e. deletes the in-progress prescription. It doesn't behave that way for edits though.. it would cancel the edit

**Comment by mark-prins** [comment] 2023-02-13 02:55
After discussion w @DhanyaHerath @craigdrown @Pauline-mSupply we've decided to try and implement in the quickest way possible.

## New Proposed Solution

- Add a button (`Save & Close`?) to step 2 and step 3 of Dispensing in Mobile ( though please put to the right of `Cancel`,  the `Cancel` button must remain on the left ):
  -  ![image](https://user-images.githubusercontent.com/65875762/173487100-ce4de934-9951-4895-a1fc-132e35795468.png)
- When this button is clicked, exit out of dispensing without deleting the prescription in 'cn' state
- Update the 'Customer Invoices' list:
  - Remove the exclusion of confirmed prescriptions from the 'current' tab
  - Clicking any 'cn' prescription will take the user back to step 2 of the dispensing flow
  - The dispensing parameters will be pre-populated with the previously entered details
- There is no requirement for any changes to how finalised prescriptions are handled/displayed - so retain current behaviour, i.e:
  - Patient history will continue show a patient's finalised dispensing history (believe un-finalised ones will not show up here - to be double checked)
    - ![image](https://user-images.githubusercontent.com/65875762/173491371-d26eb789-6e44-451f-84e2-cc2212ffd949.png)
  - Finalised prescriptions will continue to show up as a 'Past' customer invoice (weird - but this is current behaviour, and it is not editable 🤷)
    - ![image](https://user-images.githubusercontent.com/65875762/173491722-901aa017-a564-4855-b003-b96de3f9545e.png)
    - ![image](https://user-images.githubusercontent.com/65875762/173491423-93bef4aa-ca54-41a1-8a2f-73ab9722a555.png)
- Rename `Finalise` to `Confirm`
- If a payment has been entered on this `Confirm` screen:
  - Add a message 'you have entered a payment, this prescription must be finalised' (or similar) 
  - Disable `Save & Close` ( this button will re-enable if the payment is cleared )

**Comment by DhanyaHerath** [comment] 2023-02-13 03:07
thanks for writing that up @mark-prins!

**Comment by craigdrown** [comment] 2023-02-16 21:14
Thanks @mark-prins  - can the  'you have entered a payment, this prescription must be finalised'  message include "if you want to save the prescription you must clear the payment details" Thanks.

**Comment by arjunSussol** [comment] 2023-02-21 11:45
Hi @DhanyaHerath is it OK to start working on this issue?

**Comment by DhanyaHerath** [comment] 2023-02-23 02:52
Hi @arjunSussol sorry for the late reply - are you free to do this work now? Would you be able to give me an idea of how long you think it will take? I am happy for you to start working on this after that

**Comment by arjunSussol** [comment] 2023-02-23 06:39
@DhanyaHerath I have read the design and discussion and thought I need at least 10 working days for development.

**Comment by DhanyaHerath** [comment] 2023-02-24 04:45
@arjunSussol ok, thanks for letting me know! Please go ahead with the work - and do you have someone to review?

**Comment by JonnaQuismundo** [comment] 2023-04-21 04:36
hi @arjunSussol put it under job code [NFM_CUST] CI NFM3 - Customisations

**Comment by arjunSussol** [comment] 2023-04-21 08:58
@mark-prins @DhanyaHerath @JonnaQuismundo a PR has been submitted for this issue.
Please, have a look at the PR: #5175

**Comment by alainsussol** [comment] 2023-06-07 02:20
Merged in version 8.6.5

**Closed by alainsussol** 2023-06-07 02:20 UTC
Labels: Type: Feature, Priority: unconfirmed, Customization: Ivory Coast, Status: In PR

**Comment by AnushaUp** [comment] 2023-06-07 05:54
## Testing

Tested in: Mobile `v8.6.5`
Steps to reproduce or otherwise test the changes of this PR:

- [ ] Go to `Dispensing`
- [ ] Create a prescription
- [ ] There is a new button `Save & Close` in step 2 and 3 of prescription. Once you click this button, the prescription will be saved as confirmed transaction/prescription and go back to dispensing main page.
- [ ] A confirmed prescription should be visible to current tab on customer invoice. Once you click that confirmed prescription, it will take to Dispensing page and all previous saved values should be visible as it is.
- [ ] For a finalized prescription and ci, it will be as previously. Just navigate to ci page only.
- [ ] If payment module is enabled and have a total value > 0 calculated for dispensed item then `Save & Close` will be disabled and a modal generated that `You have entered a payment, this prescription must be finalised. If you want to save the prescription you must clear the payment details`. Either you have to finalise by clicking Finalise button(renamed from `Confirm`) it delete it by clicking `Cancel` button
- [ ] Otherwise create a confirmed or finalized prescription
- [ ] Only finalized prescription should be visible to patient history.
- [ ] Check confirmed prescription with insurance policy and payment type, both should be worked perfectly.
- [ ] For existing confirmed prescription, the payment type, discount rate and insurance policy should be set as set previously.
- [ ] Insurance policy should sync between mobile and desktop.
- [ ] One more thing you will notice that, the prescription will remain confirmed if you just go back with back arrow button
- [ ] Better to check by enabling/disabling the payment module and insurance policy module

**Comment by alainsussol** [comment] 2023-06-07 23:18
@AnushaUp I would be surprised if it is the right behaviour. @arjunSussol what do you think ?

**Comment by AnushaUp** [comment] 2023-06-08 04:59
Got issue while creating prescription. Issue created [HERE](https://github.com/openmsupply/mobile/issues/5220)

**Comment by AnushaUp** [comment] 2023-06-08 10:14
@arjunSussol @DhanyaHerath   and what about the vaccination module?? Its still making the prescription in finalize state directly.

**Comment by DhanyaHerath** [comment] 2023-06-09 02:28
Thanks for checking @AnushaUp! That should be fine - CDI do not use the vaccination module (phew!)
