### ISSUE TITLE
Stocktake: Reason should be mandatory if available

### ISSUE THREAD

**Issue by arjunSussol** [openmsupply/mobile#4974] opened 2022-10-20 07:32 UTC
## Describe the bug

In Stocktake, if reason column is visible then it must be set. We should not process further or can't finalize if reason is not set. But it is broken in recent version of mobile.
Must fix it.

### To reproduce

Steps to reproduce the behaviour:

1. The reason setting must be done in mSupply desktop side by following [Activate reason](https://docs.msupply.org.nz/preferences:options)
2. In mobile, create a stocktake
3. Go to `Batches` of any item, it display list of available batch for that item.
4. Set the `counted doses` lower/higher than `snapshot doses`
5. Then the arrow button in `Reason` column must be enable, by click it you can set reason
6. Set reason for some items and ignore for some.
7. Click finalize button
8. All process done without setting reason for all or none item.

### Expected behaviour

If Reason is visible then it must be set, don't allow to finalize stocktake

### Proposed Solution

If Reason is visible then it must be set, don't allow to finalize stocktake with an alert.

- If reason is activated in mSupply desktop, then reason must be set in mobile for each item.
- There should be alert when clicking Finalize button if reason doesn't set for all items.
- The alert `The reason must be set for each item before finalizing stocktake`
- If reason is not activated then, we should finalize without interruption.

### Version and device info

- App version:
- Tablet model:
- OS version:

**Comment by sworup** [comment] 2022-10-26 02:48
@arjunSussol please write the proposed solution in a bit more detail, maybe break it down into steps.

Some questions that arise:

- What would happen if no reason is available?
- Are we going to make reason mandatory for all of the times.
- What type of alert, with what info and where should we see the alert?
- Are we disabling finalise button or have the alert show when finalise is clicked?

**Comment by sworup** [comment] 2022-11-14 04:29
@arjunSussol progress on this?

**Comment by arjunSussol** [comment] 2022-11-15 10:40
> @arjunSussol progress on this?

@sworup not yet.
I think we should have a discussion and valid proposed solution before starting this.

**Comment by arjunSussol** [comment] 2022-11-16 08:27
> @arjunSussol please write the proposed solution in a bit more detail, maybe break it down into steps.
> 
> Some questions that arise:
> 
>     * What would happen if no reason is available?
> 
>     * Are we going to make reason mandatory for all of the times.
> 
>     * What type of alert, with what info and where should we see the alert?
> 
>     * Are we disabling finalise button or have the alert show when finalise is clicked?

Thanks @sworup proposed solutions updated

**Comment by sworup** [comment] 2022-12-23 05:52
Resolved with #5029

**Closed by sworup** 2022-12-23 05:52 UTC
Labels: Priority: normal, Bug: production, Effort: small, Status: In PR, Type: Enhancement

**Comment by AnushaUp** [comment] 2023-01-23 06:36
## Testing
Tested in `V8.6.2-rc04`

Steps to reproduce or otherwise test the changes of this PR:

- [ ] Enable reason (positive and negative) from desktop
- [ ] Sync to mobile well
- [ ] Create an stocktake and set reason for some of its batch and ignore for some
- [ ] If at least one batch misses the reason then you can't finalize the stocktake
- [ ] When click the finalize button alert `The reason must be set for each item before finalizing stocktake` popped up.
- [ ] Repeat the test by disabling the reason from desktop and clicking finalize button
- [ ] If reason is disabled then one can easily finalize stocktake.

**Comment by AnushaUp** [comment] 2023-01-23 08:01
@arjunSussol Working as expected **-PASSED-**
