### ISSUE TITLE
Tonga would like to be warned if they are dispensing >1 dose of HPV vaccine 

### ISSUE THREAD

**Issue by DhanyaHerath** [openmsupply/mobile#5014] opened 2022-11-30 20:08 UTC
## Is your feature request related to a problem? Please describe.

From Jess: 

> 
> A request from the team in Tonga has come in to whether we can limit the HPV to one dose (e.g. can not be dispensed twice in mobile) or alternatively, a pop-up saying: “This patient has already received one dose, are you sure you want to dispense another dose”.
> 
> The reason for this request is that it will significantly cut down the number of accidental duplicate dispensing in the system, which from what has been communicated is one of the larger data cleaning issues they are having. 
> 
> The team there would like to use the approach of having a Warning pop up if a patient has already had a dose. They have not provided a timeframe they would like this warning to pop-up - but I think we can be conservative with it to allow for the possibility that things are back entered more than 1/2 days late. 
> 
> The reason for not creating a hard limit is that there might be a future dose for patients, so we don’t to box ourselves in :)

## Describe the solution you'd like

- Make a store preference not global preference, and hard code the 7 days validation.
- If user enable the preference then mobile vaccination will check if the vaccine from same department(item.department) has been issued within 7 days to same patient.
- Confirmation alert: `This patient has already received one dose, are you sure you want to dispense another dose`, we need `Yes` and `No` for confirmation. Once we click `Confirm` or `OK and Next` button, the above alert should be visible. If we click `Yes` then we dispense the same vaccine to that patient otherwise don't proceed ahead and keep the vaccination page open.
A warning pop up if a second dose of a vaccine in the same category is prescribed within 7 days. We could consider making this 7 days period editable, but the MVP version would just have it hardcoded. 

## Implementation

TO BE DISCUSSED 

## Describe alternatives you've considered

TO BE DISCUSSED 

## Additional context

- They separate out the HPV and Covid vaccines using item category 2 (Categories are COVID and HPV) 
- I've heard that Tonga may be on a feature branch of mobile?

## Jobcode 
TGAVAC:DD

**Comment by DhanyaHerath** [comment] 2022-12-01 03:11
Please work on a design and estimated hours for this work before starting on it, thanks!

**Comment by ujwalSussol** [comment] 2022-12-01 04:01
@sworup  and @arjunSussol  : Could you come up with a design plus hours needed.  Once done, I am thinking you could present your findings in a meeting....  The Server we are talking about is the `Tonga Vax` server.

**Comment by sworup** [comment] 2022-12-01 06:10
@ujwalSussol @DhanyaHerath @arjunSussol 

### Proposed solution for discussion

These are a few things that come to mind:

- I presume we do this when a new batch is selected at the very end of the vaccination step form.
- When vaccination is selected it triggers selectVaccine action that sets vaccine to state in VaccinePrescriptionActions. This is triggered at
 https://github.com/openmsupply/mobile/blob/9ecf8683e74d9cad797191f44c500ca3cd6f5fe6/src/widgets/Tabs/VaccineSelect.js#L187

  https://github.com/openmsupply/mobile/blob/9ecf8683e74d9cad797191f44c500ca3cd6f5fe6/src/widgets/Tabs/VaccineSelect.js#L251

If we replace this dispatch by a newly created (that we will create) checkPredispensedBeforeSelect action and do these steps we should be fine.

- Check if the user selected vaccine is HPV vaccine by checking Item.category.
- If not HPV we call the VaccinePrescriptionActions.selectVaccine selector dispatch. 
- if HPV
- Have a selector call for patient vaccination history selector and check if the patient has been dispensed this vaccine within the last 7 days.
  https://github.com/openmsupply/mobile/blob/9ecf8683e74d9cad797191f44c500ca3cd6f5fe6/src/selectors/patient.js#L15-L34

> The above code is selecting non-vaccine history but it won't be hard to create a selector of vaccine history only.

- If yes dispatch for a popup 
- Otherwise we call the VaccinePrescriptionActions.selectVaccine selector dispatch.

**Comment by DhanyaHerath** [comment] 2022-12-02 03:32
@sworup thanks for that! Some comments: 
- This can be applied for __all__ vaccine categories, not just HPV - so if you try to dispense a Covid vaccine twice within a week, it should still show the popup. 
- I agree it will have to come at the end, when they select the item. It's unfortunate that they have to fill in all of the patient details first but that's just how it is! 
- I've heard that there is a separate branch for Tonga, is that correct? Could you link the branch for me please?
- Would it be possible to make the "7 days" a preference, rather than hardcoded? I'm a bit worried they'll ask us to change quickly...
- Could we get a time estimate for this please?

**Comment by sworup** [comment] 2022-12-02 06:33
@DhanyaHerath 

> I've heard that there is a separate branch for Tonga, is that correct? Could you link the branch for me, please?

It looks like tonga has v8.2.3 installed. We can create a branch off of [8.2.3 tag](https://github.com/openmsupply/mobile/tree/v8.2.3) and start from there. 

> - Would it be possible to make the "7 days" a preference, rather than hardcoded? I'm a bit worried they'll ask us to change quickly...

Yes we can

- Could we get a time estimate for this, please?

It seems @arjunSussol would work on this. I will discuss this with him and give an estimated time. 
I am expecting around 20-30 hours, which would be around 3-4 workdays.

**Comment by ujwalSussol** [comment] 2022-12-02 06:53
@DhanyaHerath   We had a heated debate during our `10 minutes` standup. 

 I was for making our Mobile master compatible for both `Kiribati`  and `Tonga`.  So the idea was to update the master and the Tonga datafile compatible for the latest Mobile...  Otherwise it complicates for support folks ... we need to know Tonga Vax are on a special version.  

So the preference would be to have the Mobile master compatible for all mobile deployment.

**Comment by arjunSussol** [comment] 2022-12-02 11:58
@DhanyaHerath @sworup @ujwalSussol 
After discussion and local testing, we have to estimate about 3 to 5 days depends on complexities.
I have some points before starting this:

1) If we are going to validate all items that are vaccines (item has already isVaccine field in both desktop and mobile side) then no need to care about item category.
2) If we differentiate vaccine based on item category then we should be cleared that mobile is accepting `item_category.description` not `item_category2.description`. So better to keep existing `item_category.description` and end user should be aware about this functionality. Otherwise we need to change code in mobile if go with `item_category2`
3) 7 days period preference: We need this preference in mSupply desktop and should be editable. This preference should be set in cloud as general preference not store specific because we need same period in all over the mobile sites to validate.
4) As we need to add preference on desktop, we have to make changes there too. Also, do we need this 7 days period visible in mobile site? If yes then can add it to mobile > Setting page similar to sync settings.
5) Confirmation alert: `This patient has already received one dose, are you sure you want to dispense another dose`, we need `Yes` and `No` for confirmation. Once we click `Confirm` or `OK and Next` button, the above alert should be visible. If we click `Yes` then we dispense the same vaccine to that patient otherwise don't proceed ahead and keep the vaccination page open.

We are going to deal with patient vaccination history that have all records from all stores instead of respective site store.
Please, give your opinion as we need to update proposed solution.

**Comment by sworup** [comment] 2022-12-05 06:40
> * We do need to check all vaccine items, but we should only alert if the same type of vaccine is being dispensed multiple times over 7 days, so we will need to use the item_category2.

Why check other categories if we are not gonna alert? Do we keep a log?

> * Ok, good to know...I think we should start sending item category 2 through to mobile. Does the item.category_2 field not get sent at all? Or is it the `item_category2` table that doesn't get sent? If at least the field is sent, that should be enough.

@DhanyaHerath Just looking at the mobile code, our mobile app only syncs `ItemCategory` into `item.category` which is `item_category` table and field from mSupply. Neither `item_category2` table nor the field is synced to mobile.

Unless we are sending item_category2 as item_category sync data. But upon my inspection it is not the case.

**Comment by arjunSussol** [comment] 2022-12-05 07:12
@ujwalSussol @DhanyaHerath @sworup
If we skip the `item_category2` works then we can do rest in 5 working days which includes development, testing and apk building.

As `item_category2` is not consuming by mobile, if we need it then we have to create its fresh schema and need to link with item. After using this client needs to be re synced mobile data which would be time consuming for syncing too. Also, we need extra time to implement this into mobile and we may need more than 5 working days.

**Comment by ujwalSussol** [comment] 2022-12-05 13:48
@arjunSussol   @sworup   :  Talking with @arjunSussol  today, I mentioned the point that we should control this feature with a preference of some sort....  Let us discuss tomorrow.

**Comment by DhanyaHerath** [comment] 2022-12-05 22:40
> Why check other categories if we are not gonna alert? Do we keep log?

@sworup We should always alert if a vaccine of the same category is dispensed twice within a period of 7 days. 

@arjunSussol @ujwalSussol Thanks all for the estimates and design! I'll take this back to Jess to check whether we should go ahead with this work based on the 5+ day estimate.

**Comment by ujwalSussol** [comment] 2022-12-06 07:35
@DhanyaHerath   @jagoje  :  

Further discussion with @sworup   and @arjunSussol  : We have a confirmed plan. 

@arjunSussol  will update the plan here with screenshots so that @jagoje and everyone will know what the final outcome will look like. 

https://docs.google.com/document/d/10nQeySzggs4ScaoQbrBRg1A8bu5qZtP6pCjRLnuUdHs/edit

**Comment by arjunSussol** [comment] 2022-12-06 09:59
> @DhanyaHerath @jagoje :
> 
> Further discussion with @sworup and @arjunSussol : We have a confirmed plan.
> 
> @arjunSussol will update the plan here with screenshots so that @jagoje and everyone will know what the final outcome will look like.
> 
> https://docs.google.com/document/d/10nQeySzggs4ScaoQbrBRg1A8bu5qZtP6pCjRLnuUdHs/edit

I have updated above docs with detailed plan and tentative timeline.

**Comment by jagoje** [comment] 2022-12-08 07:02
Thanks Everyone for all the work, 

Reviewing this now.

**Comment by bijaySussol** [comment] 2022-12-08 14:34
Chipping In, something controlling via preference on desktop is been registered [issue](https://github.com/sussol/msupply/issues/11170)  as well. 

So sort of we heading toward a right path.
Please consider updating above issue

Thanks

**Comment by DhanyaHerath** [comment] 2022-12-12 01:46
Hey team @arjunSussol @sworup @ujwalSussol Thanks so much for that detailed estimate! That was great - so helpful to think through. 

Given we don't have specific funding for this, I think we'll have to reduce the scope, so still do this work but: 
- Make the preference a store preference, like the rest of the mobile prefs 
- We can hardcode the "7 days" rather than trying to set that as a global preference
- And we can use item.department (which looks like it is already sent to mobile?) as the category rather than using item_category2. 

How does that sound?

**Comment by DhanyaHerath** [comment] 2022-12-12 23:51
Fantastic, thank you all! Please use the job code if you are working on this :)

**Comment by DhanyaHerath** [comment] 2022-12-14 23:57
@arjunSussol now that you're starting working on this, could you give me a quick estimate of when you think it will be done? Nothing too detailed, just maybe which week we should expect the work done by. Thanks Arjun!

**Comment by sworup** [comment] 2022-12-15 05:28
@DhanyaHerath we have hit a potential snag with this issue.
The issue is Tonga does not save prescription data (as current mobile vax module version mandates) which means it relies on transactions in the database to get the vaccine name, id etc. This might mean we would only get vax history of current store, which in turn restricts us from check if the vaccine category was dispensed to the client in last X days in all stores. 

@arjunSussol is further investigating this but the above conclusion is what it most likely looks like. I would let him finish the investigation before we say it with 100% confidence.

If that is the case, we have 3 options:

1. Upgrade tonga to use the current mobile version, and update the database data, it will be a lot of syncs but we would get proper vax history and could check to span all stores.
2. Whenever a vaccine is selected in the final transaction creation phase, as soon as the vax name is selected by the client we do a get request to mSupply which in turn would do a check and return an object with its results (isAllowedToDispense: true/false, numberOfOccurances: 0 or a number, daysChecked: last x days (number)}. This would be the easiest implementation if we absolutely need all store checking but the implications are the feature would no longer be available offline, and there will be a slight delay when user select a vaccine which can be annoying.
3. Accept that we would not be able to check spanning all stores and only check in current tablet's data.

**Comment by arjunSussol** [comment] 2022-12-15 11:24
@DhanyaHerath I am trying to deliver it to you by the end of next week if the progress goes well.

After discussion with @sworup I noticed that we can get vaccination history records from all sites belong to selected current patient. So, no need to worry for now as I am not going to depend on current store data.

Just made a commit which get all vaccination history of selected patient.

**Comment by sworup** [comment] 2023-01-11 08:39
Resolved with #5014

**Closed by sworup** 2023-01-11 08:39 UTC
Labels: Priority: normal, Type: Feature, Effort: large, Status: In PR
