### ISSUE TITLE
Summary of bugs found during TESTING: Indicators

### ISSUE THREAD

**Issue by diegoevangelisti** [openmsupply/mobile#2824] opened 2020-05-07 03:17 UTC
## Describe the bug

Summary of bugs that raised while testing #1935.

1 - **Viewing indicator data**
- The indicator dropdown correctly toggles between different sets of indicator data. **--FAILED**--

Toggling between HIV / REGIMEN doesn't work as expected. For instance, I couldn't get any REGIMEN data in the example below.

HIV option selected (all good):

<img width="1147" alt="Screen Shot 2020-05-07 at 3 01 21 PM" src="https://user-images.githubusercontent.com/32987464/81250308-be356d80-9074-11ea-8033-03f25a4f59c5.png">

REGIMEN option selected (see error):

<img width="1147" alt="Screen Shot 2020-05-07 at 3 01 26 PM" src="https://user-images.githubusercontent.com/32987464/81250315-c2618b00-9074-11ea-8438-06ec3420c43d.png">

2- **Design issue found while creating a new Supplier Requisition (No HIV program)**

See toggle: `Hide over stocked / Show over stocked`, IMHO it looks quite strange, maybe the right side could be aligned center or right, otherwise font size reduced?

<img width="1147" alt="Screen Shot 2020-05-07 at 3 10 40 PM" src="https://user-images.githubusercontent.com/32987464/81251090-9cd58100-9076-11ea-83cf-55bc34b5057b.png">

### To reproduce

See explanations above.

### Expected behaviour

See comments above.

### Proposed Solution

N/A.

### Version and device info

- App version: v5.0.0-rc3
- Tablet model: AVD
- OS version: Android 9.0 API 28

### Additional context

While testing #1935.

**Comment by wlthomson** [comment] 2020-05-07 07:05
@diegoevangelisti gracias hermano! Me podrias hacer un favor y crear un issue por cada problema (como yo hacia la ultima vez)? De esa manera es un poco mas facil de organizarme!

![hagalepues](https://user-images.githubusercontent.com/43223637/81264504-a02c3500-9095-11ea-947c-4f0d520216ef.jpeg)

Hagale pues!

**Comment by wlthomson** [comment] 2020-05-07 07:23
Closing as duplicate of #2825, #2826.

**Closed by wlthomson** 2020-05-07 07:23 UTC
Labels: 5.0.0-rc3, Bug: development, Docs: not needed, Priority: high

**Comment by diegoevangelisti** [comment] 2020-05-10 20:12
> @diegoevangelisti gracias hermano! Me podrias hacer un favor y crear un issue por cada problema (como yo hacia la ultima vez)? De esa manera es un poco mas fácil de organizarme!
> 
> Hagale pues!
> 
> UPDATE: no te preocupes hermano, el trabajo ya esta hecho 🤣!

@wlthomson Sure, will do it next time if that makes your life easier hermano  (Sino... plomo 😅🤣)
