### ISSUE TITLE
Sensor: vast difference shown in temperature log of CCE app, Vaccine Module & Blue Maestro app for given time range

### ISSUE THREAD

**Issue by ArpitaSussol** [openmsupply/mobile#3604] opened 2021-02-24 08:31 UTC
## Describe the bug

Vast difference shown in temperature log of CCE app, Vaccine Module & Blue Maestro app for given time range

### To reproduce

1. Put the Sensor in Refrigerator for almost half an hour
2. Setup the given sensor in all three app CCE, Vaccine Module & Blue Maestro app
3. See error. Huge margin difference shown in all three log report.
[vaccine-module-24-02-2021-1344.xlsx](https://github.com/openmsupply/mobile/files/6034458/vaccine-module-24-02-2021-1344.xlsx)
[Blue-Maestro.xlsx](https://github.com/openmsupply/mobile/files/6034459/Blue-Maestro.xlsx)
[cce-app-log-for-24-feb.xlsx](https://github.com/openmsupply/mobile/files/6034460/cce-app-log-for-24-feb.xlsx)

### Expected behaviour

There should be less marginal difference in temperature in these app.

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: v7.0.0-rc7
- Tablet model: Lenovo
- OS version: 8.1

**Comment by joshxg** [comment] 2021-02-25 02:09
@katherine-sussol @wlthomson are either of you able to take a look at this one?

**Comment by katherine-sussol** [comment] 2021-02-25 03:14
@joshxg Can take a look, sounds like a strange one!

**Comment by katherine-sussol** [comment] 2021-02-25 04:07
One thing - in the attached logs, it looks like the Blue-Maestro export has a calibration set of 13.9 which adds that amount to the temperature for each log (probably resetting this to 0 will help make it less confusing for testing!)

<img src="https://user-images.githubusercontent.com/65875762/109101210-2cc1f400-778b-11eb-9d82-3f503ad49a88.png" width="250" height="500">  <img src="https://user-images.githubusercontent.com/65875762/109101257-4400e180-778b-11eb-8567-6490a8fde634.png" width="250" height="500">

E.g. 
- 17.1 is actually 17.1 - 13.9 = 3.2 degrees celsius
- 15.8 is actually 15.8 - 13.9 = 1.9 degrees celsius 

Which more or less lines up with the cce app logs. Not sure why the vaccine module ones are off though! Will keep 👀

**Comment by katherine-sussol** [comment] 2021-03-01 04:50
Hmm I'm having some trouble reproducing an inconsistency between the BlueMaestro vs Mobile Vaccine module - they seem to be reporting the same temps for almost identical timestamps on my end (after accounting for device-specific settings, e.g. Calibration/TimeZones).

It's a bit odd that the vaccine module logs don't have anything after 1:06pm in the attachment - I think weird stuff is happening with the logging intervals when the sensor is set up in two apps separately. Is it a valid use case for two apps to be hooked up to 1 sensor? @joshxg (soz I don't know who else to @)

E.g. 
- App 1 (Mobile in this case) sets logging interval to 1min
- App 2 (CCE in this case) sets logging interval to 5min (sensor logs every 5 mins but App 1 still thinks it's 1min and timestamps all the logs with this assumption).

**Comment by joshxg** [comment] 2021-03-01 04:53
Technically possible, but we should limit our testing to having a sensor hooked up to one app (one instance of mSupply Mobile or mSupply ColdChain), exactly because of the reason of resetting logging intervals (which happens after a download). 

I think if the tests were done with the same sensor in both mSupply mobile and mSupply coldchain downloading at the same time, this would not happen in the wild and it's probably not worth investing to much time into..

**Comment by katherine-sussol** [comment] 2021-03-01 05:50
Coool, thanks. Going to close this in this case, as the inconsistencies reported look to be config/setup related (will have a think about a way to reflect this in the test template 🤔)

@ArpitaSussol for future re-tests: If you set up the sensor only in mobile and BlueMaestro (with calibration set to 0 degrees as per the screenshot) and still see huge differences between them then please do reopen 😸

**Closed by katherine-sussol** 2021-03-01 05:50 UTC
Labels: Bug: development, Module: vaccines, Priority: high

**Comment by ArpitaSussol** [comment] 2021-03-09 12:15
Tested in V7.0.0 rc9

Temperature Margin between Blue Maestro app and Vaccine module can be seen ranging from 2-3 degree celcius which is fine.
