### ISSUE TITLE
Expiration date not always correct

### ISSUE THREAD

**Issue by alainsussol** [openmsupply/mobile#2770] opened 2020-04-23 22:39 UTC
## Describe the bug

The batches expiry dates are different between mobile and desktop . It seems that they have one day difference (1 day earlier in Mobile than in Desktop). I checked a couple and they all have the same problem of one day difference. I have an example where the Expiry date of a batch shows 1st of May on Desktop and 30th of April and one shows 31st of May in desktop and 30th of May mobile. The datafile is the Ivory Coast cloud server. Mine dates back to the 27th of March and the store is NZERE.

### To reproduce

Use IC Cloud server datafile
1. Login to N'ZERE Store
2. Check the current stock for ABACAVIR/LAMIVUDINE 600/300 MG CP
3. Compare with is displayed in Mobile for that Item/batch. Do a sync to make sure to have the latest data

### Screenshots
Desktop
![image](https://user-images.githubusercontent.com/11624516/80156011-e1e6b700-8590-11ea-87ce-23822fdcc966.png)

Mobile
![image](https://user-images.githubusercontent.com/11624516/80155955-c9769c80-8590-11ea-9d84-3d241026106f.png)

### Expected behaviour

The Expiry dates between mobile and desktop for the same item/batch  item line

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: v5.0.0RC1
- Tablet model: Galaxy tab A (SM-T510)
- OS version: Android

**Comment by joshxg** [comment] 2020-04-23 22:41
@alainsussol interesting! Is this everywhere? You can view expirations in the `Current Stock` page, by clicking on a row, or in `Supplier Invoice Page`, or in `Stocktakes` also

**Comment by alainsussol** [comment] 2020-04-24 14:58
@joshxg 
It seems to be everywhere. The expiry date when clicking on a row in the Current Stock shows only month and year but the month shows April instead of May. 

![image](https://user-images.githubusercontent.com/11624516/80225320-e8207600-8618-11ea-9bab-8ce5e545706a.png)


In supplier invoices it is the same, there is a difference of one day.
Desktop
![image](https://user-images.githubusercontent.com/11624516/80226080-eacf9b00-8619-11ea-9630-f456b6fd74d9.png)

Mobile
![image](https://user-images.githubusercontent.com/11624516/80226401-4f8af580-861a-11ea-9c70-cf28334baccf.png)

For the Stocktake, I cannot check because the Batch icon on finalised stocktake is unresponsive (Nothing happens when I click on it)

**Comment by wlthomson** [comment] 2020-04-25 09:27
Hmm, haven't looked into this, but looks like a time offset might be being introduced somewhere? Could be when the record is formatted for outgoing sync by desktop or when its parsed on incoming sync by mobile, but the usual culprit is an inconsistency between the date representation when a date object is converted to and from a string (is everything using ISO dates)?

**Comment by wlthomson** [comment] 2020-04-27 23:30
OK, found it.

Desktop isn't specifying the time offset/zone (`Z` for UTF/GMT), so mobile is introducing a time adjustment which is knocking out the date slightly. 

So, looks like this is a desktop-side fix, not mobile (I suspect `ISO date` is being used instead of `ISO date GMT`).

Will open a desktop issue for this and leave this open until resolved desktop side.

**Comment by wlthomson** [comment] 2020-04-28 01:00
Update: desktop PR [here](https://github.com/sussol/msupply/pull/6144).

**Comment by wlthomson** [comment] 2020-05-01 00:41
Update: desktop PR merged. 

@alainsussol Should be fixed now! Can you please confirm this is fixed (or if not, confirm still replicable)?

**Comment by alainsussol** [comment] 2020-05-04 18:54
@wlthomson 
Hi Will,
I didn't forget. I jut had other work these last 2 days, preparing for the training I am giving tomorrow and some translation. Will get to it Wednesday at the latest...

**Comment by wlthomson** [comment] 2020-05-05 02:00
@alainsussol No worries, no rush!

**Comment by wlthomson** [comment] 2020-05-11 23:46
@alainsussol Going to bump this to `v5.1.0`. Know you're busy. No rush.

**Comment by wlthomson** [comment] 2020-06-15 00:46
Revisiting this with new info! I think this might be a duplicate of #2946?

**Comment by alainsussol** [comment] 2020-06-15 19:16
@wlthomson 

I know it is working now as I have retested it (See #6143). 

> Revisiting this with new info! I think this might be a duplicate of #2946?

In all the tests I have done, the server and the mobile device where on the same timezone (Eastern time) so from I read in the description of #2496 I don't think it is a duplicate.

**Comment by wlthomson** [comment] 2020-06-18 02:47
@alainsussol Thanks!

Closing as no longer replicable.

**Closed by wlthomson** 2020-06-18 02:47 UTC
Labels: 5.0.0-rc1, Bug: development, Module: dispensary, Priority: high

**Comment by nishaSussol** [comment] 2020-08-05 06:02
Moving to Done, as not replicable again.
