### ISSUE TITLE
Reason displayed as Not applicable rather than the reason you chose

### ISSUE THREAD

**Issue by alainsussol** [openmsupply/mobile#994] opened 2019-05-21 23:45 UTC
Build Number:2.3.3

Description: When entering a reason in a stocktake, from time to time the reason is displayed as Not Applicable even if they selected a reason from the list. They reckon it might be because when changing field the cursor moves to the line below rather than the next field to the right. It doesn't happened all the time  

Reproducible: Yes but not all the time 

Reproduction Steps:  Start a stocktake, put a quantity different than the snapshot quantity, add a reason and if you are unlucky the eason will display Not applicable rather than the reason you chose.

Comments: It seems to display properly in the cloud server though.

**Comment by wlthomson** [comment] 2019-05-22 05:20
Confirmed can replicate and will look at a fix asap.

**Comment by wlthomson** [comment] 2019-05-28 02:49
Reassigning to Josh as he is already aware of this problem and has done some work in vaccines on it.

**Comment by Chris-Petty** [comment] 2019-05-28 03:27
@joshxg regarding this issue there is a couple problems I think? It's not just showing as "Not applicable", it's not saving the reason at all (esp. if you use onscreen keyboard "next" button). I've also had the reason saved to the wrong row (the last one edited).

Given that above hint...
https://github.com/openmsupply/mobile/blob/master/src/pages/StocktakeEditPage.js#L168-L170
```javascript
// Apply stock change
stocktakeItem.setCountedTotalQuantity(database, quantity);
// Start cascade of reason selection based on currentStocktakeItem
if (usesReasons) this.assignReason(stocktakeItem);
// Then update currentStocktakeItem to be the one just edited (so assign reason 
// applies to what ever the last row was currentStocktakeItem)
this.setState({ currentStocktakeItem: stocktakeItem });
```

I'm currently in the context of this file fixing #1000 , so pretty keen to just dig into this issue

**Comment by wlthomson** [comment] 2019-05-28 04:16
> @joshxg regarding this issue there is a couple problems I think? It's not just showing as "Not applicable", it's not saving the reason at all (esp. if you use onscreen keyboard "next" button). I've also had the reason saved to the wrong row (the last one edited).
> 
> Given that above hint...
> https://github.com/openmsupply/mobile/blob/master/src/pages/StocktakeEditPage.js#L168-L170
> 
> ```js
> // Apply stock change
> stocktakeItem.setCountedTotalQuantity(database, quantity);
> // Start cascade of reason selection based on currentStocktakeItem
> if (usesReasons) this.assignReason(stocktakeItem);
> // Then update currentStocktakeItem to be the one just edited (so assign reason 
> // applies to what ever the last row was currentStocktakeItem)
> this.setState({ currentStocktakeItem: stocktakeItem });
> ```
> 
> I'm currently in the context of this file fixing #1000 , so pretty keen to just dig into this issue

As @joshxg said in his PR, the next `stocktakeItem` is being selected before the reason is applied, so it makes sense that the reason would be applied to it. The idea of the fix he currently has is that is short-circuits the `stocktakeItem` from being updated in this way (but there is a problem with it, as he has outlined). So I think the issue you are describing is the same as the one @joshxg has identified.

**Closed** 2019-05-28 22:13 UTC
Labels: Bug, Effort: small, Priority: Immediate
