### ISSUE TITLE
User should be able to select from available master lists to add items in various pages

### ISSUE THREAD

**Issue by ujwalSussol** [openmsupply/mobile#1212] opened 2019-09-13 08:20 UTC
## Is your feature request related to a problem? Please describe.
"Add item from master icon" to show the possible master list for dispensing or ordering.

Currently the "Add item from master icon" on mobile tablet simply add all items from multiple master list that the store is assigned to. We now need to show a list of master list and for the user to select and use the list. 

Issued raised from support : 
https://support.msupply.org.nz/cerb6/profiles/ticket/FR-5234-VJ

## Describe the solution you'd like
For ordering : 
We need to show the master list that is visible on current store and as well as in the store where the order is placed. 

For dispensing to a non store customer  : 
We need to show all master list that the store is associated with.

For dispensing to a store customer  : 
We need to show the master list that is visible on current store and as well as in the customer store [ I wonder if this is possible ]

## Describe alternatives you've considered
none

## Additional context

The Solomons and other users would expect this feature.

We will need a design for people to approve.

**Comment by joshxg** [comment] 2019-09-13 11:14
@ujwalSussol currently there is a big refactor happening - I would suggest that this wait till afterward -  I think it should be finished next week.

In the meantime some information:

- Adding items to a `SupplierRequisition` adds all items in any master list that is relaated to the mobile store
- Adding items to a `CustomerInvoice` adds all items from all of the Customers master lists.

So it seems the change should:

`SupplierRequisition`:
- Open a modal with the mobile stores master lists to choose from.
- We need to possibly add a new master list to the mobile database which is a combination of all so the option is there?

`CustomerInvoice`
- Show a modal to display all master lists from the customer, as well as any from the mobile store (if the customer is external, then they won't have a master list, is this right?)
- Do we also need an option to add items from all master lists of the customer?

This is very easy if you don't have the option to add all items from all master lists

**Comment by joshxg** [comment] 2019-09-13 11:17
Sorry, I should have read the ticket first. It sounds like a multi-select modal would be needed, in which case it would be a new component and a little more work, but still quite easy.

**Comment by ujwalSussol** [comment] 2019-09-16 06:34
Sure let us know when @sworup   can proceed.

**Comment by joshxg** [comment] 2019-10-15 03:11
@ujwalSussol @sworup 

This PR : #1355 contains the refactor for data table and is the blocker for this. Once that has been merged, there's not reason this can't start being worked on. 3.0.0 should be released a short time after that PR has been merged. I don't imagine this will be into 3.0.0, though

I think it would save a lot of time for everyone if we have some discussion on the design and how this would be implemented as we don't currently have a component that covers this use case

**Comment by sworup** [comment] 2019-10-31 05:37
@ujwalSussol @joshxg sounds good. Let me know when we are ready to work on this.

**Comment by joshxg** [comment] 2019-10-31 05:46
@sworup I think whenever.

I thinking that - having a component similar to `AutoCompleteSelector` - which allows for multiple selection would be a good idea, what do you think? 

I am not sure if we need to have a search bar? I think there are not that many master lists, it should be ok without?

**Comment by andreievg** [comment] 2019-11-07 03:31
While we are on the subject of item selection in mobile. A few things to consider
* Would be great to maintain consistent functionality between all pages
* Another feature that intersect with this one is having the ability to select multiple items from item select
* Stocktake has quite a different way of selecting items to the rest of the app

I would envision item selection modal having a toggle on each item that we want to select (similar to stocktake item selection), and having ability to toggle items from master lists.
Off course only items with no quantity entered should be de-selectable

**Comment by joshxg** [comment] 2019-11-07 06:31
I think they're really good ideas. Does that mean you just use one modal for both item and add from master list for all pages? I guess there is no reason for a add from master list if you can toggle items from a master list?

Just playing around.. obviously ugly but maybe an idea..

<img width="1126" alt="image" src="https://user-images.githubusercontent.com/35858975/68365290-19090d80-0195-11ea-8f79-eb59741bd8ce.png">

**Comment by Chris-Petty** [comment] 2019-11-07 21:28
@craigdrown sez
"![image](https://user-images.githubusercontent.com/7684221/68428996-1ef10400-0212-11ea-8e20-fa9245c1f2e0.png)"

Fair idea, makes it straight forward if simple. I do worry about user feedback though, if one supplier shows a selector thing and another supplier doesn't with no explanation, that isn't ideal. Equally the case if there is _no_ master list.

**Comment by sworup** [comment] 2019-11-11 05:56
@joshxg @Chris-Petty @andreievg 
Maybe we can use the same interface used for customer, item, supplier list etc. and just make it multi-selectable. (Actually we can use that for customer, item, supplier list but that is for discussion on some other day.) 

@andreievg for multi item selectable, you mean adding another interface after the master list selections that has the list of selectable items accumulated from the master list right? We can add a checkbox or a toggle button in the side that says selected, Not selected or something.

**Comment by joshxg** [comment] 2019-11-11 06:14
@sworup 

I think we can just concentrate on master list for this issue - see how it goes and then we can work on items after. Probably best to get the support ticket all sorted.

I think your idea is good. Possibly it would be easier to create a new component which does multi select, as it will need state and some further logic i.e. extra buttons .. `MultiSelectSelector` - I think that would be easier anyway

**Comment by Gwalior-84** [comment] 2019-11-11 09:37
Just adding a +1 for this.  The 60 mobile sites we just installed in PNG use multiple master lists, but they would NEVER order all of them at once - so current functionality is not satisfactory.  Their 'normal' order is a combination of two master lists.  Definitely need the ability to select 1 _or more_ master lists to populate the requisition.

**Comment by Chris-Petty** [comment] 2019-11-14 01:54
@sworup Just to clarify, this issue should just be focusing on multiple select of master lists and we can make new issues handling rolling out consistency in other areas.

It'd be good to make a v3.1.0 release including all the fixes since 3.0.0, badges and ideally this too. Are you available to work on this and make a PR by the end of your Monday?

**Comment by sworup** [comment] 2019-11-14 05:22
@Chris-Petty I am working on this right now. Should be finished by Monday.

**Comment by sworup** [comment] 2019-11-19 15:37
This is how it looks (sorry my emulator was really slow):

![neVoSJ8zFj](https://user-images.githubusercontent.com/683452/69160901-6466d880-0b12-11ea-8120-5c98c342091d.gif)

**Comment by joshxg** [comment] 2019-12-04 19:41
Closed with #1551

**Closed by joshxg** 2019-12-04 19:41 UTC
Labels: Docs: needed, Effort: small, Feature, Priority: normal

**Comment by Rebecca367** [comment] 2019-12-04 20:49
## Testing
This PR only work on SupplierRequisition. There are some issues while testing it on customer invoices. i will issue the matter.
Steps to reproduce or otherwise test the changes of this PR:

- [x ] Click `Add from masterlist` button on SupplierRequisition.
- [x ] Select one or more masterlists from the list of options.
- [x ] See if the items from the masterlist show up in the invoice. 
- [x ] The items should be there and according to the masterlist selected. There may not be overlap or duplications.

**Comment by emilyporrello** [comment] 2019-12-18 20:20
Docs updated

Added screenshots for adding items from a master list in Customer Invoices and Supplier Requisitions
https://docs.msupply.foundation/en:mobile:user_guide:customer_inv
https://docs.msupply.foundation/en:mobile:user_guide:supplier_requisitions
