### ISSUE TITLE
Patient search in Vaccination Module returning bad results

### ISSUE THREAD

**Issue by adamdewey** [openmsupply/mobile#4511] opened 2021-11-23 23:14 UTC
## Describe the bug

The patient search functionality in the Vaccination Module is not returning reliable results.

A search for a known patient first/last name combination is not returning the patient (despite the patient being present in the database). 

### To reproduce

Steps to reproduce the behaviour:

1. Go to patient search in the Vaccination Module
2. Enter the last name for a known patient
3. Enter the first name for the known patient
4. See whether patient is returned in the results

Note this does not seem to happen for every patient - unsure exactly what determines whether a particular patient will be returned or not. Needs further digging!

Example video (_sensitive content_): https://drive.google.com/file/d/1fbwrKBi8GEYOUG1XIzRQ5lguDIi2tbFf/view?usp=sharing

### Expected behaviour

Search returns the patient searched for. 

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: 8.3.0-rc1
- Tablet model: Lenovo TB-X505N
- OS version: Android 10

### Additional context

This is on an a system with the `'sync all patients everywhere'` set-up

**Comment by katherine-sussol** [comment] 2021-11-23 23:54
I don't know what's going on behind the scenes yet! But I've found a consistent way to reproduce 'weird' (maybe not the same root cause but it seems to fall into the general 'app search behaviour is not consistent with the UI form') behaviour:
- Enter valid last name
- Enter valid first name
- Clear the last name (always no results)
- Try to enter anything into the last name field (first name field gets ignored)

**Comment by katherine-sussol** [comment] 2021-11-26 01:30
Maaaaybe, hopefully, 🙏  closed by #4514. If not we will have to reopen and have another 👀

**Closed by katherine-sussol** 2021-11-26 01:30 UTC
Labels: Bug: ????, Status: In PR

**Comment by ArpitaSussol** [comment] 2021-12-07 10:53
Tested in v8.4.0-rc2

### Testing

- [x] Go to patient search in the Vaccination Module
- [x] Enter the last name for a known patient
- [x] Enter the first name for the known patient
- [x] See whether patient is returned in the results
