### ISSUE TITLE
Add uninstall script to dev_scripts

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#1053] opened 2019-07-07 22:03 UTC
## Describe 

During development it is often necessary to reinitialise the mobile app. It would be helpful to have a script to reduce overhead involved in repeated manually uninstallation.

# To reproduce

N/A.

# Expected behaviour

N/A.

# Version and device info

- App version: 2.3.4
- Tablet model: All
- OS version: All

# Additional context

N/A.

**Comment by joshxg** [comment] 2019-08-01 04:46
Closed by #1054

**Closed by joshxg** 2019-08-01 04:46 UTC
Labels: Docs: not needed, Effort: small, Priority: Low, devOps

**Comment by Chris-Petty** [comment] 2019-08-13 00:20
Reviewed the PR and didn't read the issue. If the issue is reinitialising the app then the better script would just wipe the app data, not uninstall it?

**Comment by joshxg** [comment] 2019-10-11 09:08
## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [x] Uninstall the app using `./dev_scripts/uninstall.sh`
