### ISSUE TITLE
App freezes after clicking on Create Automatic Order in SupplierRequisitionPage

### ISSUE THREAD

**Issue by diegoevangelisti** [openmsupply/mobile#1639] opened 2019-12-03 22:20 UTC
## Describe the bug

After pressing the button `Create Automatic Order` in SupplierRequistionPage the application freezes (I waited for more than 10 mins and nothing) and there is no way to navigate back. (Only option: Force Stop)

![Screen Shot 2019-12-04 at 10 22 28 AM](https://user-images.githubusercontent.com/32987464/70093246-dd267280-1684-11ea-85ca-a3662fc5efde.png)

### To reproduce

1. Go to Supplier Requisitions Page
2. Create a New Requisition or edit a current one
3. Press the button `Create Automatic Order`

### Expected behaviour

The application shouldn't freeze. Even If the option Create Automatic Order doesn't apply for this requisition (no items available to be added) the button should be disabled, a modal would pop up explaining this or do nothing. 

### Version and device info

mobile v3.0.4
Android Emulator (Android 9.0)
Tablet Lenovo (Android 8.1.0)

**Comment by joshxg** [comment] 2019-12-04 01:46
Duplicate of #1640 - closing

**Closed by joshxg** 2019-12-04 01:46 UTC
Labels: Bug: development, Docs: not needed, Effort: small
