### ISSUE TITLE
Vaccine module testing results

### ISSUE THREAD

**Issue by alainsussol** [openmsupply/mobile#3126] opened 2020-09-12 00:52 UTC
### Testing Vaccine module

- [x] Enabling the Vaccine module will change the look of your menu page, adding an extra Vaccines button. **-PASS-**

- [x] Disabling the Vaccine module will change the look of your menu page, adding an extra Vaccines button **-PASS-**

## SUPPLIER INVOICE

- [x] With the vaccine module enabled you automatically get a few extra columns on a supplier invoice - the Location and Vaccine Vial Monitor (VVM) status columns. **-PASS-**
 
- [x] With the vaccine module Disabled you automatically have the few extra columns on a supplier invoice - the Location and Vaccine Vial Monitor (VVM) status columns disappeared

- [x] You can select a location by tapping on the arrow icon in the Location cell. This will allow you to choose a location from a list.**-PASS-**

- [x] The available locations are restricted by the item's restricted location (set up on desktop). **-PASS-**

- [x] You can also change the Vaccine vial monitor status 
           - [ ] this defaults to the lowest level when adding a SI line, **PASS**
           - [ ] but can be edited by clicking on the arrow icon in the VVM Status column **-PASS-**

## CUSTOMER INVOICE

- [x] Vaccine module automatically adds two extra columns on a customer invoice - the Doses and Breach columns. **-PASS-**

- [x] The Doses column is for the number of doses actually used (so we can account for open-vial wastage). It will automatically get populated by the item quantity * number of doses in a vial, for convenience **-PASS-**

    - [x] Changing the quantity will put the quantity with the maximum of doses for that quantity **-PASS-**

- [x] You can edit the dose column **-PASS-**

- [x] The breach column should not be editable **-PASS-**

- [x] The breach icon (an orange triangle with an exclamation) show for a row, when stock line has had a temperature breach.  **-FAIL-**

- [x] Tapping the icon will bring up a graph of the temperature breach. 

## Supplier Requisitions
Tapping on a row in your supplier requisition will show you the date of the last requisition for your vaccine, as well as other details such as the open and closed vial wastage since the last requisition.

**Comment by alainsussol** [comment] 2020-09-12 00:56
Questions to remember to ask:



When no restricted locations is defined for an item, on mobile All locations are available to be assigned to that item on a supplier invoice line.

The default VVM (lower level) is assigned only when adding new lines to supplier invoice, it is not assigned automatically to an existing supplier invoice line.

If I try to create a new supplier invoice that is not linked to a supplier requisition, I don't see any suppliers listed I can choose from even if there is one (District sanitaire de Yamassoukro)

What is supposed to be mSupply behaviour for stock quantity of a vial when you break it open. Let's say that have 10 vaccins of 10 doses each.

      I break it open and gave 1 dose to a client and give 5 doses to another client (might not be possible physically but I am asking anyway). mSupply says that I have a quantity of 9 even if technically, I have a quantity of 9.4 left. I think it's ok because you probably cannot break down a vaccine between 2 differents customers but what about patients. When dispensing a vaccine, you cannot divide the doses between patients while I feel it's possible to do that. When I was vaccinated for the Yellow fever for my trip to Ivory Coast, the nurse divided the doses of a vial between 4 patients (We had to be there at the same time) because there was a shortage of vaccine. So in mSupply I would not be able to do that...

**Comment by joshxg** [comment] 2020-09-14 10:32
@alainsussol 

thanks so much for this Alain :)!!!

- When no restricted locations is defined for an item, on mobile All locations are available to be assigned to that item on a supplier invoice line.

I think this is OK? 


- The default VVM (lower level) is assigned only when adding new lines to supplier invoice, it is not assigned automatically to an existing supplier invoice line.

Hm, do you mean SI lines which are created before enabling the vaccine module? I think it would be better to auto assign in that case also, but I am not sure. What is the current behaviour exactly..? What displays?

- If I try to create a new supplier invoice that is not linked to a supplier requisition, I don't see any suppliers listed I can choose from even if there is one (District sanitaire de Yamassoukro)

You can only create an SI on mobile for *external* suppliers, which is a trick that a lot (most) people don't realize - is that the case here also?

- What is supposed to be mSupply behaviour for stock quantity of a vial when you break it open. Let's say that have 10 vaccins of 10 doses each.

I think this is meant to be solved by using 'doses' on a CI. If the Item has quantity = 1, but doses 4, then you can issue 1 dose. This will, however, reduce the quantity by 1. This is the intended behaviour, as I believe we are assuming the CI is filled *after* the doses are given (In which case, you may give 1 out of 4 doses, but you have to throw the vial out, because vaccines do not last long after they have been opened).

- The breach icon (an orange triangle with an exclamation) show for a row, when stock line has had a temperature breach. 

Will fix this one!

**Comment by alainsussol** [comment] 2020-09-14 18:59
Hi @joshxg ,

First I want to apologize, most of these questions are not very clear as they were mumble-jumble notes I took and wanted to keep them on the issue I was testing. Put it there Friday afternoon very quickly.

> When no restricted locations is defined for an item, on mobile All locations are available to be assigned to that item on a su- When no restricted locations is defined for an item, on mobile All locations are available to be assigned to that item on a supplier invoice line.

> I think this is OK? 

Yes I think it's ok too.

> - The default VVM (lower level) is assigned only when adding new lines to supplier invoice, it is not assigned automatically to an existing supplier invoice line.

> Hm, do you mean SI lines which are created before enabling the vaccine module? I think it would be better to auto assign in that case also, but I am not sure. What is the current behaviour exactly..? What displays?

Yes the lines that have been created before enabling the Vaccine module or were created before the item has not be set as a vaccine has the edit icon disabled and a "N/A" value. After I set an item as being a vaccine then the edit icon for that item is enabled but the value is still "N/A" until I edit manually.

Example:
The Vaccine module is enabled but the following item is not setup as a vaccine yet.
![image](https://user-images.githubusercontent.com/11624516/93124966-71a01580-f698-11ea-87ce-dda8fca9f0f6.png)

Set up the item as a vaccine
 
![image](https://user-images.githubusercontent.com/11624516/93126342-34d51e00-f69a-11ea-9216-1f86663a328a.png)

after it has synced, the VVM status edit button is enabled but the value has not changed to the default value.

![image](https://user-images.githubusercontent.com/11624516/93126578-84b3e500-f69a-11ea-953e-40d33dcf5b7d.png)

> - If I try to create a new supplier invoice that is not linked to a supplier requisition, I don't see any suppliers listed I can choose from even if there is one (District sanitaire de Yamassoukro)

> You can only create an SI on mobile for *external* suppliers, which is a trick that a lot (most) people don't realize - is that the case here also?

Yes

**Comment by joshxg** [comment] 2020-09-14 19:19
> Yes the lines that have been created before enabling the Vaccine module or were created before the item has not be set as a vaccine has the edit icon disabled and a "N/A" value. After I set an item as being a vaccine then the edit icon for that item is enabled but the value is still "N/A" until I edit manually.

OK great thanks so much. I'll take a look - initial thought is to apply the first vvm status when navigating to that page, if there isn't one already applied. Awesome!

**Comment by joshxg** [comment] 2020-11-20 08:55
Thanks @alainsussol

**Closed by joshxg** 2020-11-20 08:55 UTC
