### ISSUE TITLE
Searching by policy number in `Lookup patient` seems to be not working

### ISSUE THREAD

**Issue by diegoevangelisti** [openmsupply/mobile#2749] opened 2020-04-22 05:01 UTC
## Describe the bug

In Dispensary module, new policies can be added for internal/external patients, and then can be found through Lookup patient -> Filling in `Personal policy number` or/and `Family policy number` inputs. I couldn't find a new policy that I just created, when entering its information, nothing is retrieved. See example below:

Policy previously created:

![Screen Shot 2020-04-22 at 4 46 10 PM](https://user-images.githubusercontent.com/32987464/79942060-1176c000-84ba-11ea-89cc-27ce3a4536ce.png)

 - Searching by `Personal policy number`:

![searchPolicy1](https://user-images.githubusercontent.com/32987464/79942005-e8eec600-84b9-11ea-9e61-b4edf9bb23e9.gif)

- Searching by `Personal policy number` and `Family policy number`.
**NOTE**: @wlthomson, this doesn't allow me to search, it automatically disables the button. Is it a normal behaviour when trying to search using both numbers? Otherwise I will create a separate issue. 

![SEARCHPatient2](https://user-images.githubusercontent.com/32987464/79942007-eab88980-84b9-11ea-8b54-3f1f04a89197.gif)

### To reproduce

1. Go to 'Dispensary'
2. Create a new policy to an internal or external patient.
3. Go back to Dispensary and click on `Lookup patient`
4. Enter the policy number/s.
5. See error (No results).

### Expected behaviour

All patients, with the same previously entered policy numbers, should appear on the list.

### Proposed Solution

N/A.

### Version and device info

- App version: v5.0.0.rc-1
- Tablet model: AVD
- OS version: Android 9.0 API 28

### Additional context

While testing #2678

**Comment by wlthomson** [comment] 2020-04-23 04:28
Both of these are bugs! 

Good chance that this bug will be solved by a fix for #2713. Not sure whats going on with the search button in the second bug! If you could create a second issue for that it would be appreciated!

**Comment by diegoevangelisti** [comment] 2020-04-23 05:13
> Not sure whats going on with the search button in the second bug! If you could create a second issue for that it would be appreciated!

Sure, count with that. I'll create a separate one for that specific issue!

**Comment by wlthomson** [comment] 2020-04-27 02:30
Fixed by #2778.

**Closed by wlthomson** 2020-04-27 02:30 UTC
Labels: Bug: development, Docs: not needed, Module: dispensary, Priority: high

**Comment by ArpitaSussol** [comment] 2020-04-29 10:47
Tested in v5.0.0 rc2

## Testing

- [ ] Looking up patients by policy number returns all patients with personal policy numbers containing the search string. - **PASS**
- [ ] Looking up patients by policy number returns all patients with family policy numbers containing the search string. - **PASS**
- [ ] Looking up patients by policy number returns all patients with full policy numbers containing the search string (e.g. `12-3` matches a patient with personal policy number `12` and family policy number `345`). - **PASS**

@wlthomson but clicking on searched result will redirect to the patient list page rather than specific patient detail page.
https://recordit.co/GOwnI6kwxw
is this an issue ?

**Comment by wlthomson** [comment] 2020-04-30 04:16
Thanks @ArpitaSussol!

> @wlthomson but clicking on searched result will redirect to the patient list page rather than specific patient detail page.

No worries, that's the current intended behaviour.

Moving to done :tada:.
