### ISSUE TITLE
App throws error when click on "dispense" in dispensary module

### ISSUE THREAD

**Issue by Rebecca367** [openmsupply/mobile#2563] opened 2020-03-19 10:40 UTC
## Describe the bug

App throws error messages when you click on "dispense" for a patient in dispensary. 

<img width="803" alt="Screen Shot 2020-03-19 at 11 31 03 PM" src="https://user-images.githubusercontent.com/57238075/77058660-a0676700-6a3a-11ea-82a0-89f05cccebf1.png">
<img width="838" alt="Screen Shot 2020-03-19 at 11 29 54 PM" src="https://user-images.githubusercontent.com/57238075/77058454-57afae00-6a3a-11ea-89ff-c1493cfb43b2.png">

 
### To reproduce

1. Go to 'dispensary'
2. Create a patient then Click on 'dispense'
3. See error

### Expected behaviour

go to dispense mode

### Proposed Solution

N/A

### Version and device info

- App version: v4.0.2
- Tablet model: emulator
- OS version: macOS

**Comment by joshxg** [comment] 2020-03-19 20:02
Duplicate of #2537

**Closed by joshxg** 2020-03-19 20:02 UTC
Labels: Bug: development, Docs: not needed, Effort: medium, Investigation, Module: dispensary, ONE MAJOR BUG, Priority: immediate
