### ISSUE TITLE
Kiribati (1.7.d + 1.7.e + 1.7.f) Delete vaccination events

### ISSUE THREAD

**Issue by katherine-sussol** [openmsupply/mobile#4629] opened 2022-03-16 02:53 UTC
## Is your feature request related to a problem? Please describe.

- Allow deletion of vaccination events 
- Update system to make automatic stock inventory adjustments when deleting a vaccination event (e.g. the issuing store will be refunded the vaccine stock that was erroneously recorded as being administered to the patient).
- Deleted vaccination events will be kept in the back-end for auditing purposes.

## Describe the solution you'd like

**A clear and concise description of what you want to happen.**

## Implementation

**A description of how the solution would best be implemented in the code base**

## Describe alternatives you've considered

**A clear and concise description of any alternative solutions or features you've considered.**

## Additional context
- Agreed this would be only allowed if the user is logged into the store where the transaction was created (this is to reduce mobile/desktop complexity)

**Comment by chastichno** [comment] 2022-07-20 00:28
duplicate of #4796, also closing as completed

**Closed by chastichno** 2022-07-20 00:28 UTC
Labels: Feature, Priority: unconfirmed
